### ISSUE TITLE
[comp:form] 子控件为 Switch 时，formitem 的 label 和 content 没有垂直居中

### ISSUE THREAD

**Issue by imguolao** [IDuxFE/idux#1019]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://github.com/IDuxFE/idux](https://github.com/IDuxFE/idux)

### Steps to reproduce
https://playground.idux.site/#eyJQbGF5Z3JvdW5kQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPEl4RHJhd2VyUHJvdmlkZXI+XG4gICAgPEl4Tm90aWZpY2F0aW9uUHJvdmlkZXI+XG4gICAgICA8SXhNb2RhbFByb3ZpZGVyPlxuICAgICAgICA8SXhNZXNzYWdlUHJvdmlkZXI+XG4gICAgICAgICAgPEFwcCAvPlxuICAgICAgICA8L0l4TWVzc2FnZVByb3ZpZGVyPlxuICAgICAgPC9JeE1vZGFsUHJvdmlkZXI+XG4gICAgPC9JeE5vdGlmaWNhdGlvblByb3ZpZGVyPlxuICA8L0l4RHJhd2VyUHJvdmlkZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgc2V0dXBJZHV4IH0gZnJvbSAnLi9zZXR1cElkdXguanMnXG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbnNldHVwSWR1eCgpXG48L3NjcmlwdD5cbiIsIkFwcC52dWUiOiI8dGVtcGxhdGU+XG4gIDxJeEZyb20+XG4gIFx0PEl4Rm9ybUl0ZW0gbGFiZWw9XCJ0ZXN0XCI+XG4gICAgICA8SXhTd2l0Y2ggLz5cbiAgICA8L0l4Rm9ybUl0ZW0+XG4gIDwvSXhGcm9tPlxuPC90ZW1wbGF0ZT5cbiJ9

### What is expected?
可以垂直居中

### What is actually happening?
没有垂直居中

### Environment Info 

```shell
vue: ^3.2.0
@idux/components: 1.0.0-beta.20
@idux/cdk: 1.0.0-beta.19
```

---
naiveUI 和 ant-design 都是可以居中的，建议参考实现。

**Comment by imguolao** [comment]
idux: 
![image](https://user-images.githubusercontent.com/25502024/178973806-33d0111b-d974-4110-89f7-672146d2f4ad.png)

antd
![image](https://user-images.githubusercontent.com/25502024/178974104-714ee5de-4692-487d-bb59-e956e87aa297.png)

naiveUI
![image](https://user-images.githubusercontent.com/25502024/178973964-1890f9ad-2b2d-4d37-a240-80a425db628b.png)

**Comment by danranVm** [comment]
> idux: ![image](https://user-images.githubusercontent.com/25502024/178973806-33d0111b-d974-4110-89f7-672146d2f4ad.png)


这里应该是没有把样式文件加载进来，加载样式后，应该是下面这个样子

![image](https://user-images.githubusercontent.com/25052421/178985982-c6f1f775-8c55-45e6-8c0f-bffaba52ebaa.png)

默认表单控件都是 32 px 的高度，Switch 是 28，所以Swtich 没有垂直居中。

checkbox, radio, rate, slider,  可能都有类似问题，需要一并检查一下。

**Comment by imguolao** [comment]
ant-design 的 switch 高度为 22px，在 32px 高度的 form-item 中依然是垂直居中的，应该与高度无关才对

**Comment by imguolao** [comment]
> ant-design 的 switch 高度为 22px，在 32px 高度的 form-item 中依然是垂直居中的，应该与高度无关才对

naiveUI 和 antd 的一样，可以参考下它们的样式实现。
