### ISSUE TITLE
[other:*] vscode自动关联idux文档；做到代码即文档

### ISSUE THREAD

**Issue by huangtenghui** [IDuxFE/idux#1026]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
## What problem does this feature solve?
降低上手成本及提效；vscode一键解决；

## What does the proposed API look like?
vscode、webstorm插件

**Comment by tuchg** [comment]
![image](https://user-images.githubusercontent.com/24775733/179876110-852ff9e9-0990-4f17-8100-baf999424dd8.png)

IDE其实都有支持，这也是种方案，可以延伸到通过tsdoc读取注释生成idux-site,进一步提效，降低手工文档的工作量提高组件开发、使用效率

**Comment by tuchg** [comment]
@https://github.com/IDuxFE/idux-coder
