### ISSUE TITLE
[comp:table] 表格配置固定列后，固定列的ellipsis超长省略失效

### ISSUE THREAD

**Issue by lwklwklwk** [IDuxFE/idux#1081]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link

[playground.idux.site](https://playground.idux.site/#eyJQbGF5Z3JvdW5kQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPEl4RHJhd2VyUHJvdmlkZXI+XG4gICAgPEl4Tm90aWZpY2F0aW9uUHJvdmlkZXI+XG4gICAgICA8SXhNb2RhbFByb3ZpZGVyPlxuICAgICAgICA8SXhNZXNzYWdlUHJvdmlkZXI+XG4gICAgICAgICAgPEFwcCAvPlxuICAgICAgICA8L0l4TWVzc2FnZVByb3ZpZGVyPlxuICAgICAgPC9JeE1vZGFsUHJvdmlkZXI+XG4gICAgPC9JeE5vdGlmaWNhdGlvblByb3ZpZGVyPlxuICA8L0l4RHJhd2VyUHJvdmlkZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgc2V0dXBJZHV4IH0gZnJvbSAnLi9zZXR1cElkdXguanMnXG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbnNldHVwSWR1eCgpXG48L3NjcmlwdD5cbiIsIkFwcC52dWUiOiI8dGVtcGxhdGU+XG4gIDxJeFRhYmxlIDpjb2x1bW5zPVwiY29sdW1uc1wiIDpkYXRhU291cmNlPVwiZGF0YVwiIDpzY3JvbGw9XCJzY3JvbGxcIj5cbiAgICA8dGVtcGxhdGUgI25hbWU9XCJ7IHZhbHVlIH1cIj5cbiAgICAgIDxhPnt7IHZhbHVlIH19PC9hPlxuICAgIDwvdGVtcGxhdGU+XG4gICAgPHRlbXBsYXRlICNhY3Rpb24+XG4gICAgICA8YT5hY3Rpb248L2E+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9JeFRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IFRhYmxlQ29sdW1uLCBUYWJsZVNjcm9sbCB9IGZyb20gJ0BpZHV4L2NvbXBvbmVudHMnXG5cbmludGVyZmFjZSBEYXRhIHtcbiAga2V5OiBudW1iZXJcbiAgbmFtZTogc3RyaW5nXG4gIGFnZTogbnVtYmVyXG4gIGFkZHJlc3M6IHN0cmluZ1xufVxuXG5jb25zdCBjb2x1bW5zOiBUYWJsZUNvbHVtbjxEYXRhPltdID0gW1xuICB7IHR5cGU6ICdzZWxlY3RhYmxlJywgZml4ZWQ6ICdzdGFydCcgfSxcbiAge1xuICAgIHRpdGxlOiAnTmFtZScsXG4gICAgZGF0YUtleTogJ25hbWUnLFxuICAgIGVsbGlwc2lzOiB0cnVlLFxuICAgIHdpZHRoOiAxMDAsXG4gICAgZml4ZWQ6ICdzdGFydCcsXG4gICAgY3VzdG9tQ2VsbDogJ25hbWUnLFxuICB9LFxuICB7XG4gICAgdGl0bGU6ICdBZ2UnLFxuICAgIGRhdGFLZXk6ICdhZ2UnLFxuICAgIHdpZHRoOiAxMDAsXG5cbiAgfSxcbiAge1xuICAgIHRpdGxlOiAnQ29sdW1uIDEnLFxuICAgIGRhdGFLZXk6ICdhZGRyZXNzJyxcbiAgICB3aWR0aDogMTUwLFxuICAgIGtleTogJ0NvbHVtbiAxJyxcbiAgfSxcbiAge1xuICAgIHRpdGxlOiAnQ29sdW1uIDInLFxuICAgIGRhdGFLZXk6ICdhZGRyZXNzJyxcbiAgICB3aWR0aDogMTUwLFxuICAgIGtleTogJ0NvbHVtbiAyJyxcbiAgfSxcbiAge1xuICAgIHRpdGxlOiAnQ29sdW1uIDMnLFxuICAgIGRhdGFLZXk6ICdhZGRyZXNzJyxcbiAgICB3aWR0aDogMTUwLFxuICAgIGtleTogJ0NvbHVtbiAzJyxcbiAgfSxcbiAge1xuICAgIHRpdGxlOiAnQ29sdW1uIDQnLFxuICAgIGRhdGFLZXk6ICdhZGRyZXNzJyxcbiAgICB3aWR0aDogMTUwLFxuICAgIGtleTogJ0NvbHVtbiA0JyxcbiAgfSxcbiAge1xuICAgIHRpdGxlOiAnQ29sdW1uIDUnLFxuICAgIGRhdGFLZXk6ICdhZGRyZXNzJyxcbiAgICB3aWR0aDogMTUwLFxuICAgIGtleTogJ0NvbHVtbiA1JyxcbiAgfSxcbiAge1xuICAgIHRpdGxlOiAnQ29sdW1uIDYnLFxuICAgIGRhdGFLZXk6ICdhZGRyZXNzJyxcbiAgICB3aWR0aDogMTUwLFxuICAgIGtleTogJ0NvbHVtbiA2JyxcbiAgfSxcbiAge1xuICAgIHRpdGxlOiAnQ29sdW1uIDcnLFxuICAgIGRhdGFLZXk6ICdhZGRyZXNzJyxcbiAgICB3aWR0aDogMTUwLFxuICAgIGtleTogJ0NvbHVtbiA3JyxcbiAgfSxcbiAge1xuICAgIHRpdGxlOiAnQ29sdW1uIDgnLFxuICAgIGRhdGFLZXk6ICdhZGRyZXNzJyxcbiAgICBrZXk6ICdDb2x1bW4gOCcsXG4gIH0sXG4gIHtcbiAgICB0aXRsZTogJ0FjdGlvbicsXG4gICAga2V5OiAnYWN0aW9uJyxcbiAgICBmaXhlZDogJ2VuZCcsXG4gICAgd2lkdGg6IDEwMCxcbiAgICBjdXN0b21DZWxsOiAnYWN0aW9uJyxcbiAgfSxcbl1cblxuY29uc3QgZGF0YTogRGF0YVtdID0gW11cbmZvciAobGV0IGkgPSAwOyBpIDwgMTAwOyBpKyspIHtcbiAgZGF0YS5wdXNoKHtcbiAgICBrZXk6IGksXG4gICAgbmFtZTogYEVkcndhcmQgYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWAsXG4gICAgYWdlOiAzMixcbiAgICBhZGRyZXNzOiBgTG9uZG9uIFBhcmsgbm8uICR7aX1gLFxuICB9KVxufVxuXG5jb25zdCBzY3JvbGw6IFRhYmxlU2Nyb2xsID0geyB3aWR0aDogMTUwMCwgaGVpZ2h0OiAzMDAgfVxuPC9zY3JpcHQ+XG4ifQ==)

### Steps to reproduce
进入页面，table出现横向滚动条，查看效果

### What is expected?
表格配置固定列后，固定列的ellipsis超长省略正常显示

### What is actually happening?
表格配置固定列后，固定列的ellipsis超长省略无效，字符超出框体

### Environment Info 

```shell
pnpm vite
```

**Comment by danranVm** [comment]
最后一列 ellipsis 会失效，其他情况不会。
