### ISSUE TITLE
[comp:checkbox] 使用按钮样式的多选框组时，多选无法生效

### ISSUE THREAD

**Issue by sisphs** [IDuxFE/idux#1133]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
https://playground.idux.site/#eyJQbGF5Z3JvdW5kQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPEl4RHJhd2VyUHJvdmlkZXI+XG4gICAgPEl4Tm90aWZpY2F0aW9uUHJvdmlkZXI+XG4gICAgICA8SXhNb2RhbFByb3ZpZGVyPlxuICAgICAgICA8SXhNZXNzYWdlUHJvdmlkZXI+XG4gICAgICAgICAgPEFwcCAvPlxuICAgICAgICA8L0l4TWVzc2FnZVByb3ZpZGVyPlxuICAgICAgPC9JeE1vZGFsUHJvdmlkZXI+XG4gICAgPC9JeE5vdGlmaWNhdGlvblByb3ZpZGVyPlxuICA8L0l4RHJhd2VyUHJvdmlkZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgc2V0dXBJZHV4IH0gZnJvbSAnLi9zZXR1cElkdXguanMnXG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbnNldHVwSWR1eCgpXG48L3NjcmlwdD5cbiIsIkFwcC52dWUiOiI8dGVtcGxhdGU+XG4gIDxJeFNwYWNlIHZlcnRpY2FsPlxuICAgIDxJeENoZWNrYm94R3JvdXAgdi1tb2RlbDp2YWx1ZT1cInZhbHVlXCIgOmRhdGFTb3VyY2U9XCJkYXRhU291cmNlXCIgYnV0dG9uZWQ+PC9JeENoZWNrYm94R3JvdXA+XG4gIDwvSXhTcGFjZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmltcG9ydCB7IENoZWNrYm94RGF0YSB9IGZyb20gJ0BpZHV4L2NvbXBvbmVudHMvY2hlY2tib3gnXG5cbmNvbnN0IHZhbHVlID0gcmVmKFsnYmVpamluZyddKVxuXG5jb25zdCBkYXRhU291cmNlOiBDaGVja2JveERhdGFbXSA9IFtcbiAgeyBrZXk6ICdiZWlqaW5nJywgbGFiZWw6ICdCZWlqaW5nJyB9LFxuICB7IGtleTogJ3NoYW5naGFpJywgbGFiZWw6ICdTaGFuZ2hhaScgfSxcbiAgeyBrZXk6ICdndWFuZ3pob3UnLCBsYWJlbDogJ0d1YW5nemhvdScgfSxcbiAgeyBrZXk6ICdzaGVuemhlbicsIGxhYmVsOiAnU2hlbnpoZW4nIH0sXG5dXG48L3NjcmlwdD5cbiJ9

### Steps to reproduce
见重现链接

### What is expected?
checkbox组件，使用按钮样式的多选框组时，可以进行多选

### What is actually happening?
checkbox组件，使用按钮样式的多选框组时，多选无法生效

### Environment Info 

```shell
@idux/cdk: ^1.0.0-rc.5 => 1.0.0-rc.6
@idux/components: ^1.0.0-rc.5 => 1.0.0-rc.6
@idux/pro: ^1.0.0-rc.5 => 1.0.0-rc.6
 vue: ^3.2.37 => 3.2.37
```

**Comment by danranVm** [comment]
复现链接有点问题。

**Comment by sisphs** [comment]
链接已更新。
