### ISSUE TITLE
[pro:table] table设置ellipse后会使悬浮组件失效

### ISSUE THREAD

**Issue by threedayAAAAA** [IDuxFE/idux#1200]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[playground](https://playground.idux.site/#eyJQbGF5Z3JvdW5kQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPEl4RHJhd2VyUHJvdmlkZXI+XG4gICAgPEl4Tm90aWZpY2F0aW9uUHJvdmlkZXI+XG4gICAgICA8SXhNb2RhbFByb3ZpZGVyPlxuICAgICAgICA8SXhNZXNzYWdlUHJvdmlkZXI+XG4gICAgICAgICAgPEFwcCAvPlxuICAgICAgICA8L0l4TWVzc2FnZVByb3ZpZGVyPlxuICAgICAgPC9JeE1vZGFsUHJvdmlkZXI+XG4gICAgPC9JeE5vdGlmaWNhdGlvblByb3ZpZGVyPlxuICA8L0l4RHJhd2VyUHJvdmlkZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgc2V0dXBJZHV4IH0gZnJvbSAnLi9zZXR1cElkdXguanMnXG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbnNldHVwSWR1eCgpXG48L3NjcmlwdD5cbiIsIkFwcC52dWUiOiI8dGVtcGxhdGU+XG4gIDxJeFByb1RhYmxlXG4gICAgOmNvbHVtbnM9XCJjb2x1bW5zXCJcbiAgICA6ZGF0YVNvdXJjZT1cImRhdGFcIlxuICAgIGhlYWRlcj1cIlBybyBUYWJsZVwiXG4gICAgOmxheW91dFRvb2w9XCJ7IHNlYXJjaGFibGU6IHRydWUgfVwiXG4gICAgOnRvb2xiYXI9XCJ0b29sYmFyXCJcbiAgICBAY29sdW1uc0NoYW5nZT1cIm9uQ29sdW1uc0NoYW5nZVwiXG4gID5cbiAgICA8dGVtcGxhdGUgI25hbWU9XCJ7IHZhbHVlIH1cIj5cbiAgICAgIDxhPnt7IHZhbHVlIH19PC9hPlxuICAgIDwvdGVtcGxhdGU+XG4gICAgPHRlbXBsYXRlICNhY3Rpb249XCJ7IHJlY29yZCB9XCI+XG4gICAgICA8YSBzdHlsZT1cIm1hcmdpbi1yaWdodDogOHB4XCI+SW52aXRlIHt7IHJlY29yZC5uYW1lIH19PC9hPlxuICAgICAgPGE+RGVsZXRlPC9hPlxuICAgIDwvdGVtcGxhdGU+XG4gICAgPHRlbXBsYXRlICNuYW1lRGVtbz1cInsgdmFsdWUgfVwiPlxuICAgICAgZGVtbyBcbiAgICAgIDxJeFBvcG92ZXIgOnNob3ctYXJyb3c9XCJmYWxzZVwiIGhlYWRlcj1cIlRpdGxlXCIgY29udGVudD1cIlRoaXMgaXMgY29udGVudC4uLlwiPlxuICAgICA8SXhJY29uIG5hbWU9XCJleGNsYW1hdGlvbi1jaXJjbGVcIi8+XG4gIDwvSXhQb3BvdmVyPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvSXhQcm9UYWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBoIH0gZnJvbSAndnVlJ1xuXG5pbXBvcnQgeyBJeEJ1dHRvbiB9IGZyb20gJ0BpZHV4L2NvbXBvbmVudHMvYnV0dG9uJ1xuaW1wb3J0IHsgSXhJY29uIH0gZnJvbSAnQGlkdXgvY29tcG9uZW50cy9pY29uJ1xuaW1wb3J0IHsgSXhUYWcgfSBmcm9tICdAaWR1eC9jb21wb25lbnRzL3RhZydcbmltcG9ydCB7IFByb1RhYmxlQ29sdW1uIH0gZnJvbSAnQGlkdXgvcHJvL3RhYmxlJ1xuXG5pbnRlcmZhY2UgRGF0YSB7XG4gIGtleTogbnVtYmVyXG4gIG5hbWU6IHN0cmluZ1xuICBhZ2U6IG51bWJlclxuICBhZGRyZXNzOiBzdHJpbmdcbiAgdGFnczogc3RyaW5nW11cbiAgZGVzY3JpcHRpb246IHN0cmluZ1xufVxuXG5jb25zdCB0b29sYmFyID0gW1xuICBoKEl4QnV0dG9uLCBudWxsLCAoKSA9PiAnTG9hZCcpLFxuICBoKEl4SWNvbiwgeyBuYW1lOiAncmVsb2FkJywgdGl0bGU6ICdyZWxvYWQnLCBvbkNsaWNrOiAoKSA9PiBjb25zb2xlLmxvZygncmVsb2FkIGRhdGEnKSB9KSxcbl1cblxuY29uc3Qgb25Db2x1bW5zQ2hhbmdlID0gY29uc29sZS5sb2dcblxuY29uc3QgY29sdW1uczogUHJvVGFibGVDb2x1bW48RGF0YT5bXSA9IFtcbiAge1xuICAgIHR5cGU6ICdpbmRleGFibGUnLFxuICAgIGNoYW5nZVZpc2libGU6IGZhbHNlLFxuICB9LFxuICB7XG4gICAgdGl0bGU6ICdOYW1lJyxcbiAgICBkYXRhS2V5OiAnbmFtZScsXG4gICAgY2hhbmdlRml4ZWQ6IGZhbHNlLFxuICAgIGN1c3RvbUNlbGw6ICduYW1lJyxcbiAgICBjdXN0b21UaXRsZTogJ25hbWVEZW1vJyxcbiAgICAgICAgZWxsaXBzaXM6IHRydWUsXG4gIH0sXG4gIHtcbiAgICB0aXRsZTogJ0FnZScsXG4gICAgZGF0YUtleTogJ2FnZScsXG4gICAgY2hhbmdlRml4ZWQ6IGZhbHNlLFxuICB9LFxuICB7XG4gICAgdGl0bGU6ICdBZGRyZXNzJyxcbiAgICBkYXRhS2V5OiAnYWRkcmVzcycsXG4gICAgY2hhbmdlRml4ZWQ6IGZhbHNlLFxuICB9LFxuICB7XG4gICAgdGl0bGU6ICdUYWdzJyxcbiAgICBkYXRhS2V5OiAndGFncycsXG4gICAgY3VzdG9tQ2VsbDogKHsgdmFsdWUgfSkgPT5cbiAgICAgIHZhbHVlLm1hcCgodGFnOiBzdHJpbmcpID0+IHtcbiAgICAgICAgbGV0IGNvbG9yID0gdGFnLmxlbmd0aCA+IDUgPyAnd2FybmluZycgOiAnc3VjY2VzcydcbiAgICAgICAgaWYgKHRhZyA9PT0gJ2xvc2VyJykge1xuICAgICAgICAgIGNvbG9yID0gJ2Vycm9yJ1xuICAgICAgICB9XG4gICAgICAgIHJldHVybiBoKEl4VGFnLCB7IGNvbG9yIH0sIHsgZGVmYXVsdDogKCkgPT4gdGFnLnRvVXBwZXJDYXNlKCkgfSlcbiAgICAgIH0pLFxuICB9LFxuICB7XG4gICAgdGl0bGU6ICdBY3Rpb24nLFxuICAgIGtleTogJ2FjdGlvbicsXG4gICAgY2hhbmdlSW5kZXg6IGZhbHNlLFxuICAgIGN1c3RvbUNlbGw6ICdhY3Rpb24nLFxuICB9LFxuXVxuXG5jb25zdCBkYXRhOiBEYXRhW10gPSBbXVxuZm9yIChsZXQgaW5kZXggPSAwOyBpbmRleCA8IDEwMDsgaW5kZXgrKykge1xuICBkYXRhLnB1c2goe1xuICAgIGtleTogaW5kZXgsXG4gICAgbmFtZTogYEVkcndhcmQgJHtpbmRleH1gLFxuICAgIGFnZTogMTggKyAoaW5kZXggJSAxMCksXG4gICAgYWRkcmVzczogYExvbmRvbiBQYXJrIG5vLiAke2luZGV4fWAsXG4gICAgdGFnczogWyduaWNlJywgJ2RldmVsb3BlciddLFxuICAgIGRlc2NyaXB0aW9uOiBgTXkgbmFtZSBpcyBFZHJ3YXJkICR7aW5kZXh9LCBJIGFtICR7XG4gICAgICAxOCArIChpbmRleCAlIDEwKVxuICAgIH0geWVhcnMgb2xkLCBsaXZpbmcgaW4gTG9uZG9uIFBhcmsgbm8uICR7aW5kZXh9LmAsXG4gIH0pXG59XG48L3NjcmlwdD5cbiJ9)

### Steps to reproduce
见上

### What is expected?
table设置ellipse后会悬浮组件正常使用

### What is actually happening?
table设置ellipse后会使悬浮组件失效

### Environment Info 

```shell
"@idux/cdk": "1.0.0-rc.9",
    "@idux/components": "1.0.0-rc.9",
    "@idux/pro": "1.0.0-rc.9",
```

**Comment by danranVm** [comment]
`@floating-ui/dom`  的问题，idux 升级到 1.0.1 @floating-ui/dom 升级到 1.0.3 结局。

**Comment by danranVm** [comment]
see  #1242
