### ISSUE TITLE
[comp:modal] 添加draggable时，IxInput无法输入

### ISSUE THREAD

**Issue by lvzero535** [IDuxFE/idux#1211]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[playground](https://playground.idux.site/#eyJQbGF5Z3JvdW5kQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPEl4RHJhd2VyUHJvdmlkZXI+XG4gICAgPEl4Tm90aWZpY2F0aW9uUHJvdmlkZXI+XG4gICAgICA8SXhNb2RhbFByb3ZpZGVyPlxuICAgICAgICA8SXhNZXNzYWdlUHJvdmlkZXI+XG4gICAgICAgICAgPEFwcCAvPlxuICAgICAgICA8L0l4TWVzc2FnZVByb3ZpZGVyPlxuICAgICAgPC9JeE1vZGFsUHJvdmlkZXI+XG4gICAgPC9JeE5vdGlmaWNhdGlvblByb3ZpZGVyPlxuICA8L0l4RHJhd2VyUHJvdmlkZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgc2V0dXBJZHV4IH0gZnJvbSAnLi9zZXR1cElkdXguanMnXG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbnNldHVwSWR1eCgpXG48L3NjcmlwdD5cbiIsIkFwcC52dWUiOiI8dGVtcGxhdGU+XG4gIDxJeEJ1dHRvbiBtb2RlPVwicHJpbWFyeVwiIEBjbGljaz1cInZpc2libGUgPSAhdmlzaWJsZVwiPk9wZW4gbW9kYWw8L0l4QnV0dG9uPlxuICA8SXhNb2RhbCB2LW1vZGVsOnZpc2libGU9XCJ2aXNpYmxlXCIgIGhlYWRlcj1cIlRoaXMgaXMgaGVhZGVyXCI+XG4gICAgPHA+U29tZSBjb250ZW50cy4uLjwvcD5cbiAgICA8cD5Tb21lIGNvbnRlbnRzLi4uPC9wPlxuICAgIDxJeElucHV0IHYtbW9kZWw6dmFsdWU9XCJ2YWx1ZVJlZlwiIHBsYWNlaG9sZGVyPVwiQmFzaWMgdXNhZ2VcIiAvPlxuICA8L0l4TW9kYWw+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2aXNpYmxlID0gcmVmKGZhbHNlKVxuY29uc3QgdmFsdWVSZWYgPSByZWYoJ+KAmOKAmScpXG48L3NjcmlwdD5cbiJ9)

### Steps to reproduce
1. modal组件里添加draggable指令
2. 内容有ixinput

### What is expected?
ixinput可以操作

### What is actually happening?
无法输入，不能聚焦

### Environment Info 

```shell
最新版本
```

**Comment by lvzero535** [comment]
firefox下modal添加draggable，文本不能被选中

**Comment by danranVm** [comment]
dup #1202 

已经修复了。
