### ISSUE TITLE
[pro:transfer] 开启搜索配置时，不支持配置placeholder

### ISSUE THREAD

**Issue by shimaokun** [IDuxFE/idux#1213]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
## What problem does this feature solve?
穿梭框源作为一个表格时，能配置多列数据，这时候开启搜索功能，需要提个用户搜索什么样的关键字才能搜到对应的数据
例如当前穿梭框源表格有资产IP和资产状态两列，需要提醒用户，搜索框处搜索只支持搜索资产IP

## What does the proposed API look like?
searchable配置支持placeholder，如下：
searchable: { source: true, sourcePlaceholder: ‘仅支持搜索资产IP’ ,target: false }

**Comment by danranVm** [comment]
@shimaokun PR, welcome
