### ISSUE TITLE
[comp:time-picker] timeRangePicker组件无法打开overlay，控制台飘红

### ISSUE THREAD

**Issue by brenner8023** [IDuxFE/idux#1223]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[playground](https://playground.idux.site/#eyJQbGF5Z3JvdW5kQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPEl4RHJhd2VyUHJvdmlkZXI+XG4gICAgPEl4Tm90aWZpY2F0aW9uUHJvdmlkZXI+XG4gICAgICA8SXhNb2RhbFByb3ZpZGVyPlxuICAgICAgICA8SXhNZXNzYWdlUHJvdmlkZXI+XG4gICAgICAgICAgPEFwcCAvPlxuICAgICAgICA8L0l4TWVzc2FnZVByb3ZpZGVyPlxuICAgICAgPC9JeE1vZGFsUHJvdmlkZXI+XG4gICAgPC9JeE5vdGlmaWNhdGlvblByb3ZpZGVyPlxuICA8L0l4RHJhd2VyUHJvdmlkZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgc2V0dXBJZHV4IH0gZnJvbSAnLi9zZXR1cElkdXguanMnXG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbnNldHVwSWR1eCgpXG48L3NjcmlwdD5cbiIsIkFwcC52dWUiOiI8dGVtcGxhdGU+XG4gIDxJeFNwYWNlPlxuICAgIDxJeFRpbWVSYW5nZVBpY2tlcj48L0l4VGltZVJhbmdlUGlja2VyPlxuICA8L0l4U3BhY2U+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuPC9zY3JpcHQ+XG4ifQ==)

### Steps to reproduce
写一个最简单的timeRangePicker组件，点击它

### What is expected?
控制台不报错，点击可以显示overlay

### What is actually happening?
timeRangePicker组件无法打开overlay，控制台飘红

![image](https://user-images.githubusercontent.com/31237954/197234233-ed2525f5-c145-4c61-b31c-cb53bb6efda5.png)

### Environment Info 

```shell
idux版本1.0.1
vue版本3.2.41
```

---
版本1.0.0-rc.8是正常的，版本1.0.0-rc.9开始是不正常的

**Comment by danranVm** [comment]
@sallerli1 修复后，记得补个测试

**Comment by danranVm** [comment]
closed #1225
