### ISSUE TITLE
[comp: grid] add grid component

### ISSUE THREAD

**Issue by zymoplastic** [IduxFE/idux#133]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
grid

#### Props

| 名称      | 说明                                                         | 类型                  | 默认值  | 全局配置 | 备注 |
| --------- | ------------------------------------------------------------ | --------------------- | ------- | -------- | ---- |
| `align`   | flex 布局下的垂直对齐方式                                    | `string`              | `top`   | -        | -    |
| `gutter`  | 栅格间隔，可以写成像素值或支持响应式的对象写法来设置水平间隔 `{ xs: 8, sm: 16, md: 24}`。或者使用数组形式同时设置 `[水平间距, 垂直间距]` | `number/object/array` | `0`     | -        | -    |
| `justify` | flex 布局下的水平排列方式：`start` `end` `center` `space-around` `space-between` | `string`              | `start` | -        | -    |
| `wrap`    | 是否自动换行                                                 | `boolean`             | true    | ✅        | -    |

#### Props

| 名称     | 说明                                                         | 类型            | 默认值 | 全局配置 | 备注 |
| -------- | ------------------------------------------------------------ | --------------- | ------ | -------- | ---- |
| `flex`   | flex 布局属性                                                | `string/number` | -      | -        | -    |
| `offset` | 栅格左侧的间隔格数，间隔内不可以有栅格                       | `number`        | `0`    | -        | -    |
| `order`  | 栅格顺序                                                     | `number`        | `0`    | -        | -    |
| `pull`   | 栅格向左移动格数                                             | `number`        | `0`    | -        | -    |
| `push`   | 栅格向右移动格数                                             | `number`        | `0`    | -        | -    |
| `span`   | 栅格占位格数，为 0 时相当于 `display: none`                  | `number`        | -      | -        | -    |
| xs       | `屏幕 < 600px` 响应式栅格，可为栅格数或一个包含其他属性的对象 | `number/object` | -      | -        | -    |
| sm       | `屏幕 >= 600px` 响应式栅格，可为栅格数或一个包含其他属性的对象 | `number/object` | -      | -        | -    |
| md       | `屏幕 >= 1024px` 响应式栅格，可为栅格数或一个包含其他属性的对象 | `number/object` | -      | -        | -    |
| lg       | `屏幕 >= 1280px` 响应式栅格，可为栅格数或一个包含其他属性的对象 | `number/object` | -      | -        | -    |
| xl       | `屏幕 >= 1720px` 响应式栅格，可为栅格数或一个包含其他属性的对象 | `number/object` | -      | -        | -    |

**Comment by zymoplastic** [comment]
@danranVm @hele10086 , 麻烦两位看下 API 是否合理

**Comment by danranVm** [comment]
> @danranVm @hele10086 , 麻烦两位看下 API 是否合理

我没什么问题。

**Comment by hele10086** [comment]
> @danranVm @hele10086 , 麻烦两位看下 API 是否合理
我也没有问题

**Comment by zymoplastic** [comment]
@danranVm, 我看到我们的断点服务里面的 key 为 `'XSmall' | 'Small' | 'Medium' | 'Large' | 'XLarge'`, 我们这里的 prop 是只提供简写(只能写 xs), 还是都支持(xs 和 XSmall 均可, XSmall 优先级高)?

**Comment by danranVm** [comment]
> @danranVm, 我看到我们的断点服务里面的 key 为 `'XSmall' | 'Small' | 'Medium' | 'Large' | 'XLarge'`, 我们这里的 prop 还有 gutter 里面是只提供简写(只能写 xs), 还是都支持(xs 和 XSmall 均可, XSmall 优先级高)?

xs 吧，这个太常用了，简写吧

**Comment by zymoplastic** [comment]
> > @danranVm, 我看到我们的断点服务里面的 key 为 `'XSmall' | 'Small' | 'Medium' | 'Large' | 'XLarge'`, 我们这里的 prop 还有 gutter 里面是只提供简写(只能写 xs), 还是都支持(xs 和 XSmall 均可, XSmall 优先级高)?
> 
> xs 吧，这个太常用了，简写吧

好的, 现在是第二种实现, 会改成第一种
