### ISSUE TITLE
[comp: affix] add affix component

### ISSUE THREAD

**Issue by jackson-yyy** [IduxFE/idux#138]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

affix

### props
|     名称     |                             说明                             |    类型     | 默认值 |
| :----------: | :----------------------------------------------------------: | :---------: | :----: |
|  offset  |         距离窗口顶部的偏移量，到达时会触发fix<br />          |   number \| { top:number. bottom:number, left:number, right:number}   |   -    |
|  container   |                        用于定位的容器，会监听容器的滚动事件，用函数返回        | () => HTMLElement \| window | () => window |
| throttleTime|   节流时间（ms）设置，用于提高性能<br />开启后affix位置更新会产生延迟   |   number    | -|

### event
|      名称      |            说明             | 回调参数 |
| :------------: | :-------------------------: | :------: |
| status-changed | 固定/非固定状态切换时的事件 | boolean  |

### slot
|      名称      |            说明             |
| :------------: | :-------------------------: |
| default | 默认插槽 |

**Comment by jackson-yyy** [comment]
@danranVm 麻烦看下api这样设计是否合理:bowtie:

**Comment by danranVm** [comment]
- offset 的 4 个 API 有点臃肿
  - 建议保留两个 offsetTop， offsetBottom（参考自 antd）
  - 或者 4 个合并成 1 个, `offset: number | { top:number. bottom:number, left:number, right:number}`, 为 number 时，默认为 top
- container 我看 antd 是一个函数，不知道他们为什么这么设计，你考虑下。
- useAbsolute 这个不需要吧，用户自己用样式去控制就好了。

**Comment by jackson-yyy** [comment]
> * offset 的 4 个 API 有点臃肿
>   
>   * 建议保留两个 offsetTop， offsetBottom（参考自 antd）
>   * 或者 4 个合并成 1 个, `offset: number | { top:number. bottom:number, left:number, right:number}`, 为 number 时，默认为 top
> * container 我看 antd 是一个函数，不知道他们为什么这么设计，你考虑下。
> * useAbsolute 这个不需要吧，用户自己用样式去控制就好了。

@danranVm 
感谢提出的建议

第一点建议采纳
第二点我也在思考container 为啥用函数返回，我再研究下
第三点，加入useAbsolute是参考了fusion design的做法，用以解决ant-design中，target容器不为window时，元素会跑到容器外的问题

参考
fusion design [https://fusion.design/pc/component/basic/affix](url)
ant-degsign的issue https://www.antdv.com/components/affix-cn/#FAQ

**Comment by danranVm** [comment]
@jackson-yyy OK, 那我没什么问题了。

**Comment by Pupils-web** [comment]
修改后的api问题不大，实现的时候注意一下内存和性能问题

**Comment by jackson-yyy** [comment]
不知这样设计是否合理：
取消useAbsolute属性，内部判断container，如果是window就采用fix定位，否则采用absolute定位，最后达到基于container进行affix的效果，也能减少prop的数量
@danranVm @Pupils-web

**Comment by danranVm** [comment]
> 不知这样设计是否合理：
> 取消useAbsolute属性，内部判断container，如果是window就采用fix定位，否则采用absolute定位，最后达到基于container进行affix的效果，也能减少prop的数量
> @danranVm @Pupils-web

恩，这样更好点。

**Comment by jackson-yyy** [comment]
> > 不知这样设计是否合理：
> > 取消useAbsolute属性，内部判断container，如果是window就采用fix定位，否则采用absolute定位，最后达到基于container进行affix的效果，也能减少prop的数量
> > @danranVm @Pupils-web
> 
> 恩，这样更好点。

ok，那我按照这样设计了
