### ISSUE TITLE
[comp:button] 是否可以给button添加一个属性，取消 button click 之后的效果

### ISSUE THREAD

**Issue by kovsu** [IDuxFE/idux#1413]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
## What problem does this feature solve?
![image](https://user-images.githubusercontent.com/82451257/212282472-31f389e2-107f-4949-8adc-30b85d7884ca.png)

有很多组件都会使用 button 组件，那么 button 组件的点击效果，在其他地方可能就会显得有些奇怪。就比如在 card footer 使用 button 组件

## What does the proposed API look like?
组件添加一个属性可以关闭点击之后的效果

**Comment by danranVm** [comment]
`<IxButton waveless >Click</IxButton>`

加个 waveless  就好了。

**Comment by kovsu** [comment]
> `<IxButton waveless >Click</IxButton>`
> 
> 加个 waveless 就好了。

那是不是应该给，card 组件的 footer的 button 添加上这个属性
