### ISSUE TITLE
[comp:select] 下拉选择器在输入时鼠标失焦后输入内容被清空了

### ISSUE THREAD

**Issue by danranVm** [IDuxFE/idux#1431]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

![image](https://user-images.githubusercontent.com/25052421/213120840-7c0c86e4-4c93-412f-b0b1-9caea0ae0db9.gif)

### Steps to reproduce

如上图在中文输入 -》 按回车键 -》输入框有内容 -》点击空白处失焦 -》 输入框内容被清

### What is expected?

输入的内容不会被清空

### What is actually happening?

输入时按了回车键情况下会被清空

**Comment by kovsu** [comment]
![select](https://user-images.githubusercontent.com/82451257/214629575-e87b6b82-a7d0-45d1-b05f-b3ceeeb6090c.gif)

**Comment by kovsu** [comment]
但是现在还有个问题就是，视频的后面。你可以看到我在修改值得时候丢失焦点，那里会出现闪屏。其实我的想法是如果输入得时候丢失焦点，值不改变。
