### ISSUE TITLE
[comp:select]IxSelect在中文输入法输入时回车，onSearch事件会失效

### ISSUE THREAD

**Issue by lyyzhh** [IDuxFE/idux#1474]
- [ ] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
前提：系统输入法为中文输入法，IxSelect组件配置searchable，multiple，@search
步骤1：光标激活select组件，输入关键字
步骤2：按回车键，此时关键字已键入组件内，同时会选中第一个选项
步骤3，手动取消掉第一个选中项（或按退格键取消），此时@search事件失效

### Environment Info
@idux/component@1.4.2

**Comment by danranVm** [comment]
**步骤2：按回车键，此时关键字已键入组件内，同时会选中第一个选项**
当你选中了一个值后，此时的搜索过程已经结束了，
`取消掉选中项`，onSearch 不触发时正常的行为。

**Comment by lyyzhh** [comment]
是清除选中后，再次输入关键字，无法触发onSearch

**Comment by danranVm** [comment]
> 是清除选中后，再次输入关键字，无法触发onSearch

我刚刚尝试了下，没有复现出来。

**Comment by danranVm** [comment]
![image](https://user-images.githubusercontent.com/25052421/221525753-38bf9af0-e9e9-435f-ab6f-6f09230a7f58.png)

**Comment by danranVm** [comment]
![select2](https://user-images.githubusercontent.com/25052421/221732085-02d224cb-396c-49c6-9eed-7760d6d40bb7.gif)
