### ISSUE TITLE
用户交流群，欢迎入群交流和讨论。

### ISSUE THREAD

**Issue by danranVm** [IDuxFE/idux#1527]
使用 微信/企业微信 扫码加群。  
对 `@idux` 有任何建议或者使用上的疑问，都可以在群里交流和讨论。

**Comment by lsymy** [comment]
新的群聊还会再建立吗

**Comment by danranVm** [comment]
> 新的群聊还会再建立吗

暂时不会了，有什么问题欢迎提 issue 吧。
