### ISSUE TITLE
[ comp:notification] useNotification 使用报错

### ISSUE THREAD

**Issue by zhuxingyao** [IDuxFE/idux#1576]
- [ ] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce

import { useNotification } from '@idux/components/notification'
const notification = useNotification()
notification.error({ title: 'error', content: `$Error code: ${ code }` })
### What is actually happening?

ts 语法报错 
类型“{ title: string; content: string; }”的参数不能赋给类型“Omit<NotificationOptions<VKey>, "type">”的参数。
  类型 "{ title: string; content: string; }" 中缺少属性 "key"，但类型 "Omit<NotificationOptions<VKey>, "type">" 中需要该属性。ts(2345)
types.d.ts(69, 5): 在此处声明了 "key"。

### Any additional comments? (optional)

其中 NotificationOptions 的 key 是必传值，文档并没有说明 key 该填什么

**Comment by danranVm** [comment]
Key 就是组件的唯一标识，跟 v-for 中的 key 是一个作用。
不过这个地方应该不是必传的，是 ts 的类型声明写错了，下个版本修复。
