### ISSUE TITLE
[comp: list] add list component

### ISSUE THREAD

**Issue by rhinonan** [IduxFE/idux#187]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

最基础的列表展示，可承载文字、列表、图片、段落，常用于后台数据展示页面。

### What does the proposed API look like?

内容涵盖：
* List: 外部包裹容器
* Item: 列表子项

关联的其他组件：
* Grid

#### List Props

参数 | 说明 | 类型 | 默认值 | 版本
-- | -- | -- | -- | --
borderless| 是否展示边框 | boolean | false |  
footer | 列表底部 | string\|v-slot:footer| - |  
grid | 列表栅格配置，与grid组件保持一致 | object | - |  
header | 列表头部 | string\|v-slot:header| - |  
layout | 设置 List.Item 布局, 设置成 vertical 则竖直样式显示, 默认横排 | horizontal\|vertical| vertical |  
loading | 当卡片内容还在加载中时，可以用 loading 展示一个占位 | boolean | false |  
loadMore | 加载更多 | string\|v-slot:loadMore | - |  
empty| 空状态 | string \| v-slot:empty|  'ix-empty'
size | list 的尺寸 | large\|medium\|small | medium|  
split | 是否展示分割线 | boolean | true |  
- | 默认不具名slot | v-slot | - |  

#### List.Item Props

参数 | 说明 | 类型 | 默认值
-- | -- | -- | --
extra | 额外内容, 通常用在 itemLayout 为 vertical 的情况下, 展示右侧内容; horizontal 展示在列表元素最右侧 | v-slot:extra | -
content | 列表元素的描述内容 | string\|slot | -
title | 列表元素的标题 | string\|slot | -

**Comment by rhinonan** [comment]
@danranVm @Usualminds review 一下 API

**Comment by danranVm** [comment]
- 类型一栏中的 slot 统一改成 v-slot:xxx
- loading 只支持 boolean 类型的就好了吧
- size 的类型应该为 `large\|medium\|small`
- actions 和 extra 是不是重复了？

**Comment by Usualminds** [comment]
- grid 支持栅格布局，建议看下这里 [grid](https://github.com/IduxFE/components/issues/133) 保持一致，如 `gutter` `column`，是否需要单列出来
- 支持一下 `dataSource` (列表数据源) 配置项，这个是列表的基础数据配置
- 建议支持 `pagination` 配置项，这个还是有使用场景的

**Comment by rhinonan** [comment]
@danranVm 
1. slot 统一修改为 v-slot:xxx
2. borderless 调整
3. loading 修改为只支持boolean，并且类型明确为 `horizontal\|vertical`
4. size 可选值 修改为 large\|medium\|small ，并且默认值为全局的size配置（是否有这个全局的功能）

@Usualminds 
1. 去除actions，只保留extra为右侧的slot
2. dataSource之前讨论过了，不支持，目前支持v-for item的形式

其他修改
1. List itemLayout属性名称 修改为layout 更加简洁
2. Item中的 description修改为content更加符合实际用途
3. List 组件 新增默认的不具名slot

**Comment by danranVm** [comment]
@rhinonan 全局配置 参考 `useGlobalConfig`, 基本上每个组件都有用到，你看下就知道怎么用了。
