### ISSUE TITLE
[comp:title] add title component

### ISSUE THREAD

**Issue by danranVm** [IduxFE/idux#188]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What does the proposed API look like?

标题栏用于各中容器的顶部，起到了内容概览和引导页级操作的作用。

## 何时使用

当需要使用户快速理解当前容器是什么以及一些快捷操作。

#### Props

| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| `title` | 标题文字 | `string\|v-slot:default` | - | - | - |
| `subTitle` | 二级标题文字 | `string\|v-slot:subTitle` | - | - | - |
| `extra` | 右侧操作区域 | `string\|string[]\|v-slot:extra` | - | - | - |
| `size` | 标题大小 | `extraLarge\|large\|medium\|small` | `large` | - | 分别对应 `h1\|h2\|h3\|h4` |
| `prefix` | 标题前缀图标 | `string\|v-slot:prefix` | - | - | - |

#### Emits

| 名称 | 说明 | 参数类型 | 备注 |
| --- | --- | --- | --- |
| `extraClick` | 右侧操作图标被点击 | `(name: string, evt: MouseEvent) => void` | `name` 为传入的 `extra` 值 |
| `prefixClick` | 前缀图标被点击 | `(evt: MouseEvent) => void` | - |

**Comment by danranVm** [comment]
@rhinonan @hele10086 麻烦 review 一下 API

**Comment by danranVm** [comment]
后续可能会增加 面包屑，标签，头像 等配置，依赖于相关组件。

**Comment by rhinonan** [comment]
没什么问题

**Comment by danranVm** [comment]
@rhinonan 新增了一个 extraClick 的 emit
