### ISSUE TITLE
[comp: popover]: add component popover

### ISSUE THREAD

**Issue by LaamGinghong** [IduxFE/idux#193]
# Popover API

- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

弹出浮层显示更详细的信息，又避免使用弹窗这种直接影响用户操作的重量级视图。

### What does the proposed API look like?
*   可以手动控制浮层显隐，并有回调；
*   浮层可以选择是否显示标题，并且标题允许用户通过传插槽的形式进行自定义；
*   浮层一定会有内容；
*   浮层可以根据用户配置选择定位对齐位置，并且可以由调用方决定是否需要自动定位；
*   浮层支持多种触发方式；
*   浮层可以由调用方决定是否需要在隐藏时销毁。

## 何时使用

需要展示一些详细信息，但又不想被弹窗打断当前其他操作。

#### Props

| 名称                   | 说明                     | 类型                       | 默认值  | 全局配置 | 备注 |
| ---------------------- | ------------------------ | -------------------------- | ------- | -------- | ---- |
| `title`                | 浮层的标题               | `string \| v-slot:title`   | -       | -        | -    |
| `content`              | 浮层内容                 | `string \| v-slot:default` | -       | -        | 必传    |
| `placement`            | 浮层的对齐方式           | `Placement`                |  `top`       | ✅        | -    |
| `visible`              | 是否显隐                 | `boolean`                  | `false` | -        | -    |
| `trigger`              | 浮层触发方式             | `OverlayTrigger`           | `click`       | ✅        | -    |
| `showDelay`            | 浮层显示延时             | `number`                   | 100       | ✅        | -    |
| `hideDelay`            | 浮层隐藏延时             | `number`                   | 100       | ✅        | -    |
| `destroyOnHide` | 隐藏时是否销毁浮层       | `boolean`                  | `false`       | ✅        | -    |
| `autoAdjust`    | 浮层被遮挡时自动调整位置 | `boolean`                  | `true`       | ✅        | -    |

#### Emits

| 名称            | 说明             | 类型                         |
| --------------- | ---------------- | ---------------------------- |
| `visibleChange` | 浮层显示隐藏回调 | `(visible: boolean) => void` |

**Comment by LaamGinghong** [comment]
@danranVm 请review

**Comment by huangtenghui** [comment]
trigger这个配置不应该是全局的，浮层的触发方式应该是根据业务来决定

**Comment by LaamGinghong** [comment]
> trigger这个配置不应该是全局的，浮层的触发方式应该是根据业务来决定

其实只是想给调用方提供一个可以选择的能力，也许某些平台是更倾向于hover的方式显示浮层，某些平台更倾向于click显示浮层

**Comment by huangtenghui** [comment]
> > trigger这个配置不应该是全局的，浮层的触发方式应该是根据业务来决定
> 
> 其实只是想给调用方提供一个可以选择的能力，也许某些平台是更倾向于hover的方式显示浮层，某些平台更倾向于click显示浮层

不是的，用click还是用hover是根据业务来的，比如有些popover的内容是要靠后台请求得来的，那这时候会使用click，有些是一次性提前全部返回的，那么用hover；

**Comment by huangtenghui** [comment]
autoAdjustPopover这个应该不会false的场景，悬浮的可视无遮挡应该是基本要求；

**Comment by LaamGinghong** [comment]
> > > trigger这个配置不应该是全局的，浮层的触发方式应该是根据业务来决定
> > 
> > 
> > 其实只是想给调用方提供一个可以选择的能力，也许某些平台是更倾向于hover的方式显示浮层，某些平台更倾向于click显示浮层
> 
> 不是的，用click还是用hover是根据业务来的，比如有些popover的内容是要靠后台请求得来的，那这时候会使用click，有些是一次性提前全部返回的，那么用hover；

组件本身是可以自己修改props来自己选择哪种方式，并不是说全局配置就不能修改的，优先级是props大于全局配置的

**Comment by LaamGinghong** [comment]
> autoAdjustPopover这个应该不会有false的场景，悬浮的可视无遮挡应该是基本要求；

表格、长列表、虚拟滚动的场景可能会不需要这个

**Comment by danranVm** [comment]
- destroyPopoverOnHide => destroyOnHide
- autoAdjustPopover => autoAdjust

这两个 API  Tooltip、Popconfirm 应该也是可以共享的，命名上精简一些吧。
另外你的默认值要给出来，不然都不知道你的全局配置的默认值是啥。

**Comment by LaamGinghong** [comment]
@huangtenghui @danranVm 更新了API

**Comment by danranVm** [comment]
- trigger 的默认值建议为 'hover'
- destroyOnHide 的默认值建议为 false
- showDelay 和 hideDelay 的默认值 500，是不是太长了点，我看 antd 都是 0.1。。。

**Comment by LaamGinghong** [comment]
> * trigger 的默认值建议为 'hover'

我觉得这种需要展示这么多详细信息的，更适合点击的场景，我目前做的这个需求就是这样。

**Comment by huangtenghui** [comment]
ok

**Comment by LaamGinghong** [comment]
@danranVm 重新review
