### ISSUE TITLE
[build] an error occured when exec `pnpm build`

### ISSUE THREAD

**Issue by coolyuantao** [IDuxFE/idux#1998]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
When using `pnpm run` to execute NPM Scripts, errors occured.

```bash
 ERROR  Unknown option: 'idux:commitizen_path'
For help, run: pnpm help run
ERROR: "build:clean" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Zhengqbbb** [comment]
ref: https://github.com/mysticatea/npm-run-all/issues/201
The [npm-run-all](https://www.npmjs.com/package/npm-run-all) package has stopped being maintained since 2018. Can switch to the [npm-run-all2](https://www.npmjs.com/package/npm-run-all2) package.
