### ISSUE TITLE
[comp: tooltip]: add component tooltip

### ISSUE THREAD

**Issue by LaamGinghong** [IduxFE/idux#200]
- [x] I have searched the [issues](https://github.com/IduxFE/idux/issues) of this repository and believe that this is not a duplicate.

### What does the proposed API look like?

这个组件和 #193 是继承关系，这个组件是 #193 Popover 的父类

**Comment by danranVm** [comment]
一定要通过继承的方式么？参考 input 和 textarea 把公共逻辑抽取出来不行吗？
