### ISSUE TITLE
 [ IxProLayout]菜单图标请求问题

### ISSUE THREAD

**Issue by Ricky816845** [IDuxFE/idux#2011]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我这边没有使用你们自带的图标，但是菜单配置会自己异步请求图标的图片，结果导致一堆404请求
有考虑更改这方面的计划吗？

![image](https://github.com/user-attachments/assets/43f74ac7-3605-461d-a79a-2acd1c559983)

### What does the proposed API look like?

至少加个配置让选怎么加载图标吧

**Comment by danranVm** [comment]
参考以下 http://ui.sangfor.com.cn/common/idux/components/icon/zh?tab=api#%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD%E5%92%8C%E9%9D%99%E6%80%81%E5%8A%A0%E8%BD%BD

我们提供了 addIconDefinitions 来静态加载图标，避免请求过多。
