### ISSUE TITLE
[comp:Menu]: add component Menu

### ISSUE THREAD

**Issue by qingshan-dev** [IduxFE/idux#229]
- [ ] I have searched the [issues](https://github.com/IduxFE/idux/issues) of this repository and believe that this is not a duplicate.

**Comment by danranVm** [comment]
为页面和功能提供导航的菜单列表。

## 何时使用

导航菜单是一个网站的灵魂，用户依赖导航在各个页面中进行跳转。一般分为顶部导航和侧边导航，顶部导航提供全局性的类目和功能，侧边导航提供多级结构来收纳和排列网站架构。

## API

### ix-menu

#### MenuProps

| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| `disabled` | 是否禁用 | `boolean` | `false` | - | - |
| `inlineCollapsed` | `inline` 模式时的菜单收起状态 | `boolean` | `false` | ✅ | - |
| `inlineIndent` | `inline` 模式时的菜单缩进宽度 | `string \| number` | `24px` | ✅ | - |
| `mode` | 菜单模式，现在支持垂直、水平和内嵌 | `vertical \| horizontal \| inline` | `vertical` | - | - |
| `theme` | 主题颜色 | `light` | `light` | ✅ | TODO: 支持 `dark` |

#### MenuEmits

| 名称 | 说明 | 参数类型 | 备注 |
| --- | --- | --- | --- |
| `click` | 点击 `ix-menu-item` 后的回调 | `{ item: IxMenuItem, key: string }` | - |

### ix-sub-menu

#### SubMenuProps

| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| `v-model:open` | 是否展开 | `boolean` | `false` | - | - |
| `disabled` | 是否禁用 | `boolean` | `false` | - | - |
| `icon` | 菜单图标| `string \| v-slot:icon` | - | - |
| `title` | 菜单标题 | `string \| v-slot:title`  | - | - |


### ix-menu-item

#### MenuItemProps

| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| - | - | - | - | ✅ | - |
| `disabled` | 是否禁用 | `boolean` | `false` | - | - |
| `icon` | 菜单图标| `string \| v-slot:icon` | - | - |
| `title` | 菜单标题 | `string \| v-slot:default`  | - | - |

### ix-menu-group

#### MenuGroupProps

| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| `icon` | 菜单图标| `string \| v-slot:icon` | - | - |
| `title` | 菜单标题 | `string \| v-slot:default`  | - | - |

**Comment by rhinonan** [comment]
1. 展开 收起这里每一个都有 subMenu 控制 这很麻烦把，这里为啥不用 openKeys 的形式？
2. ix-sub-menu 的展开收起 应该也有一个时间吧。

**Comment by rhinonan** [comment]
1. 展开 收起这里每一个都有 subMenu 控制 这很麻烦把，这里为啥不用 openKeys 的形式？
2. ix-sub-menu 的展开收起 应该也有一个时间吧。

**Comment by danranVm** [comment]
> 1. 展开 收起这里每一个都有 subMenu 控制 这很麻烦把，这里为啥不用 openKeys 的形式？
> 2. ix-sub-menu 的展开收起 应该也有一个时间吧。

1. 通常的业务场景都是用户拿到一个数组来渲染菜单，此时每个数组元素里会有一个控制是否展开的字段，直接用这个 key 去绑定 subMenu  的 open 就好了。而不需要通过遍历数组，拿到需要展开的 keys 传给 menu 组件。
2. 指 delay 的时间吗？ 我看一下好不好加吧，好实现就加上，不好实现就后面再考虑吧。
