### ISSUE TITLE
[comp:checkbox] 支持 `readonly` `autofocus` 等 props, 以及 `focus`, `blur` 方法

### ISSUE THREAD

**Issue by danranVm** [IduxFE/idux#235]
### Steps to reproduce

```html
      <input
        type="checkbox"
        class="ix-checkbox-input"
        :name="inputName"
        :checked="isChecked"
        :disabled="isDisabled"
        :trueValue="trueValue"
        :falseValue="falseValue"
        :value="value"
        v-bind="attrs"
        @change="handleChange"
      />
      <span class="ix-checkbox-inner" :tabindex="$attrs.tabindex"></span>
```
由于是使用 `span` 去模拟 `checkbox`, 所以  `v-bind="attrs"` 没有意义。

### What is expected?

支持这些属性和方法，注意：可能还有其他类似的属性和方法。

### Any additional comments? (optional)

---
| Environment | Info |
|---|---|
| @idux |     |
| Browser |     |

**Comment by liuzaijiang** [comment]
`readonly`，`focus`，`blur`已经支持；`v-bind="attrs"`还是有意义的，对于name，value这种input原生属性还是需要绑定在input上，而且autofocus不需要单独增加属性去控制，因为input本身支持autofocus字段， 通过`v-bind="attrs"`绑定到了原生input上即可
