### ISSUE TITLE
[comp: all] JS 中使用样式变量的问题

### ISSUE THREAD

**Issue by zymoplastic** [IDuxFE/idux#246]
- [x] I have searched the [issues](https://github.com/IduxFE/idux/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前只有 LESS 变量, 但是部分组件需要把一些样式写到 JS 里, 比如 `progress` 这种, 建议提供统一的 JS 样式变量, 方便后面统一修改, 维护和换肤

以某一个 PR 中的代码来举例
```
export const xx = (a: AType): string => {
  const {
    from = '#3366ff', // @primary-color

  } = a
  // ...
}
```

### What does the proposed API look like?
可以采用多种形式, 但是就是不要像上面一样写离散的代码

**Comment by danranVm** [comment]
是不是可以提供一个类似于 globalConfig 的东西，把 js 需要用到的 less 变量统一管理起来，然后用户也可以动态的修改。

**Comment by zymoplastic** [comment]
> 是不是可以提供一个类似于 globalConfig 的东西，把 js 需要用到的 less 变量统一管理起来，然后用户也可以动态的修改。

对. 不过我觉得目前暂时不去花精力思考用户该怎么动态修改, 可以先把统一管理搞出来, 后面组件都差不多了再想用户怎么配置

**Comment by unknownzjc** [comment]
这个任务我认领下。

**Comment by danranVm** [comment]
现在可以在 js 代码中获取  css variable 的值
