### ISSUE TITLE
[comp: card]feature card component

### ISSUE THREAD

**Issue by CruellyJoHn** [IduxFE/idux#28]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

- 支持设置卡片大小
- 支持设置卡片边框的显示
- 支持title自定义
- 支持卡片右上角操作区域自定义
- 支持卡片loading状态
- 支持卡片悬浮效果

### **ix-card**
参数 | 说明|类型|默认值|全局配置 |
| --- | --- | --- | --- | --- |
| `title` | 卡片标题 | `'string'|'slot'` | - | - |
| `extra` | 右上角操作区域 | `'string'|'slot'` | - | - |
| `footer` | 卡片底部操作区域 | `'slot'` | - | - |
| `bordered` | 是否有边框 | `'booelan'` | `'true'` | `'true'` |
| `hoverable` | 是否悬浮 | `'booelan'` | `'false'` | `'false'` |
| `loading` | 当卡片内容还在加载中时，可以用 loading 展示一个占位 | `'booelan'` | `'false'` | `'false'` |
| `size` | 设置按钮大小 | `'large'|'medium'|'small'` | `'medium'` |

### `事件`

| 事件名称 | 说明 | 参数 |
| --- | --- | --- |
| onExtraClicked | 当extra参数为string时，用于点击extra | event |

**Comment by danranVm** [comment]
@clfeng @danranVm 负责此组件的 review， API 设计完成后请 `@` 他们

**Comment by CruellyJoHn** [comment]
@danranVm @clfeng 麻烦大佬review下

**Comment by danranVm** [comment]
API 很克制，很棒。有几点建议：
- onExtraClicked 不建议提供，如果用户有处理事件的需求，就使用 slot 好了, 传入 string 的时候，card 只负责展示。
- bordered => borderless, 默认值为 false ，当然这个可能需要再次和大家确认一下, 理由是使用更为方便：

```html
<ix-card borderless ></ix-card>
<!-- 而不是 -->
<ix-card :bordered="false" ></ix-card>
```

**Comment by clfeng** [comment]
size 配置项的说明是指的卡片的大小吧？ 
当前api的配置项相对于antd来说是少了很多，个人觉得antd内置了很多的场景，这个我们可以后续考虑是否加上这些场景。然后再代码编写的时候可能要考虑的就是如果 以后要加上这些场景的话，代码是否好扩展
