### ISSUE TITLE
[comp: tag]feature tag component

### ISSUE THREAD

**Issue by Gilbert5210** [IduxFE/idux#29]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

 - 支持默认的6种标签tag样式
 - tag内容支持多种方式展示（设置最大高宽，超出使用省略；换行显示完整；列宽限定，换行完整）
 - 默认8中颜色区分等级，且支持自定义样式
 - 支持标签的删除操作
 - 支持默认的三种size供选择，当然也可以自定义size

### What does the proposed API look like?

# ix-tag

## API 

**Props**

| 参数      | 说明                                | 可选项                                                       | 类型    | 默认值 |
| --------- | ----------------------------------- | ------------------------------------------------------------ | ------- | ------ |
| closable  | 标签是否可以关闭                    |                                                              | Boolean | false  |
| color     | 标签颜色                            | gray\| success\| info\| lowRisk\|danger \| waring\|serious\|risk | String  | -      |
| icon      | 标签左侧图标                        |                                                              | string  | -      |
| checkable | 标签是否可以被选中             |                                                              | Boolean | false  |
| checked | 标签选中状态                        |                                                              | Boolean | false  |
| isRound   | 是否圆角形状                        |                                                              | Boolean | false  |
| level     | 数字等级(正整数),这个可以优先级放后 |                                                              | Number  | -      |

**Emits**

| 事件名称 | 说明                 | 回调函数          |
| -------- | -------------------- | ----------------- |
| close    | 关闭时的回调         | (e) => void       |
| change   | 点击标签时触发的回调 | (checked) => void |

**Slots**

| 名称    | 说明              |
| ------- | ----------------- |
| default | tag的text内容     |
| icon    | tag前面的icon内容 |

**Comment by danranVm** [comment]
@644395781 @danranVm 负责此组件的 review， API 设计完成后请 `@` 他们

**Comment by Gilbert5210** [comment]
@danranVm @Pupils-web 

review 下tag这块的设计

**Comment by danranVm** [comment]
- 建议，移除 closable, 新增 mode, 类型为：'closeable' | 'default' | 'checkable'， 默认值为 defualt
- 建议移除 closeIcon，这个建议就默认吧，真有自定义需求的时候再加。
- effect，isOval，levelNum，maxWidth，size 等 API 建议在斟酌一下。

**Comment by Gilbert5210** [comment]
@danranVm @Pupils-web 
更新了api设计了，看下没有问题就按照现在这样来进行代码设计了

**Comment by danranVm** [comment]
> @danranVm @Pupils-web
> 更新了api设计了，看下没有问题就按照现在这样来进行代码设计了

checkable => checked

不需要有一个 **标签是否可以选中** 的配置？
