### ISSUE TITLE
[comp: v-click-outside] there is a bug when using v-click-outside and overlay together.

### ISSUE THREAD

**Issue by jackson-yyy** [IDuxFE/idux#322]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/22521237/118388965-05781600-b65a-11eb-8394-7f2b04d7fe7d.png)
![image](https://user-images.githubusercontent.com/22521237/118388967-09a43380-b65a-11eb-98dc-2315cbd935de.png)

给input设置的triggerRef，然后给overlay设置的v-click-outside，设置了triggerRef的input，没有监听到click事件，导致上一个timepicker的overlay没有关闭，不知道是overlay的问题还是v-click-outside的问题
### What is expected?
设置triggerRef的dom，能在document正常监听到click事件，触发v-click-outside
### What is actually happening?
没有监听到click事件
### Any additional comments? (optional)

---
| Environment | Info |
|---|---|
| @idux |     |
| Browser |     |

**Comment by danranVm** [comment]
这块的逻辑以及被重构掉了。
