### ISSUE TITLE
[comp: progress] add Progress component 

### ISSUE THREAD

**Issue by hangboss1761** [IduxFE/idux#35]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

## Props

各类型通用的属性

| 参数          | 说明                                                         | 类型                                                         | 默认值                   |
| ------------- | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------ |
| type          | 类型，可选 `line` `circle` `dashboard`                       | string                                                       | `line`                   |
| format        | 内容的函数模板，支持插槽                                     | function(percent, successPercent) \| v-slot:format="percent, successPercent" | percent => percent + '%' |
| percent       | 百分比                                                       | number                                                       | 0                        |
| status        | 状态，可选：`success` `exception` `normal` `active`(仅限line) | string                                                       | -                        |
| hideInfo      | 是否隐藏进度数值或状态图标                                   | boolean                                                      | false                     |
| success       | 成功进度条相关配置                                           | { percent: number, strokeColor: string }                     | -                        |
| trailColor    | 未完成的分段的颜色                                           | string                                                       | -                        |
| strokeColor   | 进度条的色彩                                                 | string                                                       | -                        |
| strokeLinecap | 进度条的样式，可选：`round` `square`                         | string                                                       | `round`                  |

`type="line"`

| 参数        | 说明                               | 类型 | 默认值 |
| ----------- | ---------------------------------- | ---- | ------ |
| strokeColor | 进度条的色彩，传入 object 时为渐变 | string \| { from: string; to: string; direction: string } | - |
| strokeWidth | 进度条线的宽度，单位 px | number | 10 |

`type="circle"`

| 参数        | 说明                               | 类型 | 默认值 |
| ----------- | ---------------------------------- | ---- | ------ |
| width | 圆形进度条画布宽度，单位 px | number | 132 |
| strokeColor | 圆形进度条的色彩，传入 object 时为渐变 | string \| { from: string; to: string; direction: string } | - |
| strokeWidth | 圆形进度条线的宽度，单位是进度条画布宽度的百分比 | number | 6 |

`type="dashboard"`

| 参数        | 说明                               | 类型 | 默认值 |
| ----------- | ---------------------------------- | ---- | ------ |
| width | 仪表盘进度条画布宽度，单位 px | number | 132 |
| strokeWidth | 仪表盘进度条线的宽度，单位是进度条画布宽度的百分比 | number | 6 |

**Comment by danranVm** [comment]
@hele10086 @danranVm 负责此组件的 review， API 设计完成后请 `@` 他们

**Comment by hangboss1761** [comment]
> @hele10086 @danranVm 负责此组件的 review， API 设计完成后请 `@` 他们

Ok

**Comment by hangboss1761** [comment]
@hele10086  @danranVm 麻烦抽空帮忙review下 api  😀 😀 😀

**Comment by danranVm** [comment]
感觉文档还是按照 antd 那样来设计会比较容易区分。
把公共的 API，然后每个 type 的API 分开展示吧，现在这样看着有点晕。:cry:

**Comment by hele10086** [comment]
按照 antd 那样区分API文档把。
因为从实现上，这应该会是三个不同的组件。
只不过从场景上看都是进度条的场景，合一起方便使用而已。
如果合在一起的话在阅读起来会很不方便，而且这样也可能对实现有一定的误导性（强耦合）

**Comment by hangboss1761** [comment]
嗯嗯，区分出来更加易读，已更新
请两位 @hele10086 @danranVm 再review一下 😃

**Comment by danranVm** [comment]
是不是漏了个Props  `successPercent` ?

- 另外文档(index.zh.md)格式注意下按照 button 组件的格式来

**Comment by hangboss1761** [comment]
> 是不是漏了个Props `successPercent` ?
> 
> * 另外文档(index.zh.md)格式注意下按照 button 组件的格式来
> 
> 我这边其他问题没有了，期待 PR。

好的

遗漏了success,以及trailColor两个配置，已补上

successPercent会根据success传递的内容计算出来

**Comment by hangboss1761** [comment]
showInfo 调整为 hideInfo，默认为false，方便使用

**Comment by hangboss1761** [comment]
![image](https://user-images.githubusercontent.com/30379896/104679233-3a19a680-5728-11eb-9e73-5acb8d8032de.png)
