### ISSUE TITLE
[cdk:form] form文档优化

### ISSUE THREAD

**Issue by jackson-yyy** [IDuxFE/idux#357]
### Reproduction link

![image](https://user-images.githubusercontent.com/22521237/124348417-6795d600-dc1c-11eb-88f7-d7f998377a6c.png)

### What is expected?

1. 校验器属性应同为单数或者复数
2. 正确的文档格式

### What is actually happening?

1. 校验器validators为复数，但是asyncValidator为单数
2. 这两个属性的文档格式错误

### Any additional comments? (optional)

---
| Environment | Info |
|---|---|
| @idux |     |
| Browser |     |

**Comment by danranVm** [comment]
closed #678
