### ISSUE TITLE
[comp: Message]feature Message component

### ISSUE THREAD

**Issue by manchixue** [IduxFE/idux#36]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What does the proposed API look like?

# Message 全局提示

全局展示操作反馈信息。

### API 

- message.success(content, [duration])
- message.error(content, [duration])
- message.info(content, [duration])
- message.warn(content, [duration])
- message.remove([messageId])
- message.getContainer() 获取message消息容器

也可以通过对象的形式传递参数

- message.success(config)
- message.error(config)
- message.info(config)
- message.warn(config)
- message.create(config)

| 参数     | 说明                                      | 类型                  | 默认值 |
| -------- | ----------------------------------------- | --------------------- | ------ |
| content  | 提示内容                                  | string\|config\|vnode | -      |
| duration | 自动关闭的延时，单位秒。当设置为0时不消失 | number                | 3      |

`config`对象属性如下:

| 参数         | 说明                                    | 类型           | 默认值 |
| ------------ | --------------------------------------- | -------------- | ------ |
| content      | 提示内容                                | string\|vnode  | -      |
| duration     | 自动关闭的延时，单位秒。设置为0立即关闭 | number         | 3      |
| icon         | 自定义图标                              | string\|vnode  | -      |
| messageId          | 当前提示的唯一标志                      | string\|number | -      |
| onClose      | message关闭时触发的回调函数           | function       | -      |
| pauseOnHover | 鼠标移上时禁止自动移除                  | boolean        | true   |

## 全局方法

组件还提供全局配置和全局销毁方法

通过`useGlobalConfig`方式设置message的默认全局配置

```javascript
useGlobalConfig('message', {
  top: 100,
  duration: 2,
  maxCount: 3
});
```

options:

| 参数         | 说明                                           | 类型           | 默认值 |
| ------------ | ---------------------------------------------- | -------------- | ------ |
| duration     | 默认自动关闭延时，单位秒，设置为0立即关闭      | number         | 3      |
| maxCount     | 最大显示数, 超过限制时，最早的消息会被自动关闭 | number         | -      |
| top          | 消息距离顶部的位置                             | string\|number |        |
| pauseOnHover | 鼠标移上时禁止自动移除                         | boolean        | true   |

##### message.remove

销毁某个消息实例的方法

| 参数 | 说明                                                         | 类型                               | 默认值 |
| ---- | ------------------------------------------------------------ | ---------------------------------- | ------ |
| messageId  | 需要销毁的消息实例对应的messageId。可选参数，如果不传参数则清除所有消息。 | string\|number\|(string\|number)[] | -      |

**Comment by danranVm** [comment]
@clfeng @danranVm 负责此组件的 review， API 设计完成后请 `@` 他们

**Comment by manchixue** [comment]
@clfeng @danranVm 有空看下message的api设计
另外我打算加上单条消息鼠标移入时停止定时清除，鼠标移出后重新开启定时清除这条消息的功能

**Comment by danranVm** [comment]
看了下，我个人感觉 `ng-zorro-antd` 的API 设计会更好些？https://ng.ant.design/components/message/zh

- 全局配置
  - 使用 `useGlobalConfig` 的方式，不用额外提供 `config` 函数。
  - `prefixCls` 不提供，感觉没什么意义。
  - `rtl` 不提供，我们暂不支持
  - `getContainer` 不提供, 暂时就默认到 body 吧，有需求再加。

**Comment by manchixue** [comment]
API已修改 prefixCls rtl getContainer暂时移除 后面再看是否需要支持
