### ISSUE TITLE
issue helper

### ISSUE THREAD

**Issue by danranVm** [IDuxFE/idux#368]
- [x] I have searched the [issues](https://github.com/IduxFE/idux/issues) of this repository and believe that this is not a duplicate.

### What does the proposed API look like?

快速创建规范的 issue，参考 ：
- https://new-issue.ant.design
- https://github.com/vuejs/vue-issue-helper

**Comment by 2321605193** [comment]
> * [x] 我已经搜索了这个存储库的[问题](https://github.com/IduxFE/idux/issues)，并相信这不是重复的。
> 
> ### 这个功能解决了什么问题？
> ### 提议的 API 是什么样的？
> 快速创建规范的问题，参考：
> 
> * https://new-issue.ant.design
> * https://github.com/vuejs/vue-issue-helper

**Comment by danranVm** [comment]
closed #664
