### ISSUE TITLE
[comp:drawer] placement classname conflict

### ISSUE THREAD

**Issue by coolyuantao** [IDuxFE/idux#450]
### Steps to reproduce

See in: https://github.com/IDuxFE/idux/blob/main/packages/components/drawer/src/DrawerBody.tsx#L15

```
14:    const placement = computed(() => props.placement ?? 'right')
15:    const classes = computed(() => `ix-drawer ${placement.value}`)
16:    const isHorizontal = computed(() => placement.value === 'right' || placement.value === 'left')
```

`classes` will be a shorter classname such as: `left`, `right`, `top`, `bottom`，A prefix should be required

### Any additional comments? (optional)

---
| Environment | Info |
|---|---|
| @idux |     |
| Browser |     |

**Comment by danranVm** [comment]
closed #451
