### ISSUE TITLE
[comp:all] 所有组件的 size， 统一采用简写的方式

### ISSUE THREAD

**Issue by danranVm** [IDuxFE/idux#466]
- [ ] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.

small => sm, 
medium => md
large => lg

参考 PR： https://github.com/IDuxFE/idux/pull/464

**Comment by coolyuantao** [comment]
表单已经处理：https://github.com/IDuxFE/idux/pull/498
