### ISSUE TITLE
[comp: form] 通过setValidator设置校验函数后，校验函数不生效

### ISSUE THREAD

**Issue by sjia0307** [IDuxFE/idux#486]
### Reproduction link
https://codesandbox.io/s/idux-reproduction-template-forked-y9gdo?file=/src/HelloWorld.vue:922-934
### Steps to reproduce

1.初始化时不设置校验函数
2.通过setValidator设置[required]
3.设置完成后开始校验
### What is expected?
提示不能为空
### What is actually happening?
校验通过。输入内容再清空后，这时候输入框会爆红
### Any additional comments? (optional)

---
| Environment | Info |
|---|---|
| @idux |     |
| Browser |     |

**Comment by danranVm** [comment]
```ts
    group.get("password").setValidator([required]);
    group.get("password").validate();
```

如果你需要在设置 validator 后，直接生效，可以手动调用一下 validate 方法。
