### ISSUE TITLE
[comp:select] 在modal中使用select组件，SelectOptionContainer宽度跟SelectInput不一致

### ISSUE THREAD

**Issue by Jouryjc** [IDuxFE/idux#488]
### Reproduction link
https://codesandbox.io/s/idux-reproduction-template-forked-v4n07?file=/src/HelloWorld.vue

### Steps to reproduce
1. 在 IxModal 里使用 IxSelect
```vue
<IxModal v-model:visible="visible" header="This is header">
  <IxSelect v-model:value="singleValue" placeholder="choose Tom or Jerry">
    <IxSelectOption label="Tom" value="tom" />
    <IxSelectOption label="Jerry" value="jerry" />
    <IxSelectOption label="Speike" value="speike" disabled />
  </IxSelect>
</IxModal>
```

### What is expected?
SelectOptionContainer 宽度跟 SelectInput 保持一致

### What is actually happening?
宽度不一致
![image](https://user-images.githubusercontent.com/11925053/139658834-d6a44940-e8e2-484b-be09-42b66dcb8258.png)

### Any additional comments? (optional)

---
| Environment | Info |
|---|---|
| @idux |     |
| Browser |     |

**Comment by danranVm** [comment]
re #853
