### ISSUE TITLE
[comp:ButtonGroup] 样式丢失

### ISSUE THREAD

**Issue by imguolao** [IDuxFE/idux#501]
### Reproduction link

无

### Steps to reproduce

例子代码如下：

```vue
<template>
  <IxButtonGroup>
    <IxButton>button 0</IxButton>
    <IxButton>button 1</IxButton>
  </IxButtonGroup>
</template>
```

### What is expected?

样式按照按钮组显示（边框样式） ：

![image](https://user-images.githubusercontent.com/25502024/140882301-40f7b22f-988b-4626-ab9a-47e4bf65bc74.png)

### What is actually happening?

样式并未按照按钮组显示：

![image](https://user-images.githubusercontent.com/25502024/140881642-4008c869-dc24-4228-9b6d-a39b3923994a.png)

### Any additional comments? (optional)

---
| Environment | Info |
|---|---|
| @idux |     |
| Browser |     |

**Comment by danranVm** [comment]
最好能够写一个 mixin, 把 button-group, radio-group, checkbox-group 都统一搞定。

**Comment by Darma1106** [comment]
> 最好能够写一个 mixin, 把 button-group, radio-group, checkbox-group 都统一搞定。

尝试了一些办法，普通的butttonGroup可以用radioGroup的方案，但是像mode="dashed"的虚线按钮，没有想到比较好的解决方案。
