### ISSUE TITLE
[comp:pagination] button size has invalid value

### ISSUE THREAD

**Issue by He110te4m** [IDuxFE/idux#507]
### Reproduction link

https://github.com/IDuxFE/idux/blob/78738c2b819beaa5b52e15fc41ba518b99bb05d4/packages/components/pagination/src/Item.tsx#L85

### Steps to reproduce

The value of the size field small is illegal. And I get the warning say: "Invalid prop: custom validator check failed for prop 'size'. "

### What is expected?

no warning.

### What is actually happening?

show warning

### Any additional comments? (optional)

---
| Environment | Info |
|---|---|
| @idux |     |
| Browser |     |

**Comment by danranVm** [comment]
re #466
