### ISSUE TITLE
[comp:Icon] 部分图标丢失（文档内无法显示）

### ISSUE THREAD

**Issue by He110te4m** [IDuxFE/idux#515]
### Reproduction link

https://idux.site/components/icon/zh

### Steps to reproduce

![image](https://user-images.githubusercontent.com/16161582/141483713-ca23b64e-de5e-4516-947e-57228d4e4ceb.png)

### What is expected?

图标正常显示

### What is actually happening?

部分图标丢失

### Any additional comments? (optional)

---
| Environment | Info |
|---|---|
| @idux |     |
| Browser |     |

**Comment by danranVm** [comment]
重新部署后，已经修复了。
