### ISSUE TITLE
[comp:Input] 文档错别字

### ISSUE THREAD

**Issue by He110te4m** [IDuxFE/idux#518]
### Reproduction link

https://idux.site/components/input/zh#InputProps

### Steps to reproduce

![image](https://user-images.githubusercontent.com/16161582/141613199-e59f11e6-ae96-4c43-b26c-622e30d9e01c.png)

### What is expected?

显示“清除”

### What is actually happening?

显示“清楚”

### Any additional comments? (optional)

---
| Environment | Info |
|---|---|
| @idux |     |
| Browser |     |

**Comment by danranVm** [comment]
直接 PR 吧。
