### ISSUE TITLE
[comp:input]input设置inheritAttrs: false，导致继承input开发的业务组件样式、类名等不生效

### ISSUE THREAD

**Issue by lo56ve** [IDuxFE/idux#529]
### Reproduction link
无
### Steps to reproduce

1. 组件Test基于IxInput组件再封装，如
```
<template>
  <div>123</div>
</template>

<script>
  import { defineComponent } from 'vue';
  import { IxInput } from '@idux/components/input';

  export default defineComponent({
    name: 'Test',
    extends: IxInput,
  });
</script>
```
2. 业务中使用该test组件，此时test上所有的attrs不生效
```
<test class="pull-right"  />
```

### What is expected?
配置在Test上的属性生效
### What is actually happening?
配置在Test上的属性不生效，被清空了
### Any additional comments? (optional)
由于IxInput配置`inheritAttrs: false`，导致vue renderComponentRoot中不将组件属性赋值不生效，见
```
if (fallthroughAttrs && inheritAttrs !== false) { // 跳出
  // 将属性下传
}
```
---
| Environment | Info |
|---|---|
| @idux | 0.7.0 |
| Browser | 92.0.4515.159 |

**Comment by danranVm** [comment]
是出于什么需求，需要继承组件？

**Comment by lo56ve** [comment]
> 是出于什么需求，需要继承组件？

在input之上封装clear、close等icon逻辑

**Comment by lo56ve** [comment]
封装的业务组件Test已通过配置`inheritAttrs: true`规避

**Comment by danranVm** [comment]
不推荐直接继承组件，如果需要二次封装，直接包一层就好了。
