### ISSUE TITLE
[cdk/forms] input组件control传FormControl提示类型错误

### ISSUE THREAD

**Issue by sjia0307** [IDuxFE/idux#539]
### Reproduction link

https://codesandbox.io/s/idux-reproduction-template-forked-y9gdo?file=/src/HelloWorld.vue
### Steps to reproduce

input组件control传FormControl
### What is expected?

不提示类型错误
### What is actually happening?

提示类型错误
### Any additional comments? (optional)

---
| Environment | Info |
|---|---|
| @idux |     |
| Browser |     |

**Comment by danranVm** [comment]
@sjia0307 这个再试一下呢？应该被修复了。

**Comment by danranVm** [comment]
先关闭了，如果还有问题，就再打开。
