### ISSUE TITLE
[comp: avatar] add avatar component

### ISSUE THREAD

**Issue by TaiKyo** [IduxFE/idux#55]
- [ ] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用来代表用户或事物，支持图片、图标或字符展示。

#### AvatarProps

| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| `alt` | 图像无法显示时的替代文本 | `string` | - | - | - |
| `gap` | 字符类型距离左右两侧边界单位像素 | `number` | `4` | ✅ | - |
| `icon` | 设置自定义图标 | `string \| VNode \| #icon` | `user` | ✅ | 如果设置了 `src`, 则作为图片加载失败的 fallback 行为 |
| `shape` | 设置头像的形状 | `'circle' \| 'square'` | `'circle'` | ✅ | - |
| `size` | 设置头像的大小 | `'large' \| 'medium' \| 'small' \| number \| Record<BreakpointKey, number>` | `'medium'` | ✅ | - |
| `src` | 图片类头像的资源地址 | `string` | - | - | - |
| `srcSet` | 设置图片类头像响应式资源地址 | `string` | - | - | - |
| `onError` | 图片加载失败的事件 | `() => unknown` | - | - | 返回 false 会关闭组件默认的 fallback 行为 |

#### AvatarSlots

| 名称 | 说明 | 参数类型 | 备注 |
| --- | --- | --- | --- |
| `default` | 图片加载失败的 fallback 行为 | - | 优先级高于 `icon` |

**Comment by danranVm** [comment]
@hele10086 @danranVm 负责此组件的 review， API 设计完成后请 `@` 他们

**Comment by danranVm** [comment]
@StevieTaylor 接手该组件
