### ISSUE TITLE
[comp: layoutPro] 导航布局组件

### ISSUE THREAD

**Issue by lo56ve** [IDuxFE/idux#554]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.

### IxLayoutPro（导航布局）

| 名称               | 说明                         | 类型                     | 默认值       | 全局配置 | 备注                                                      |
| ------------------ | ---------------------------- | ------------------------ | ------------ | -------- | --------------------------------------------------------- |
| `v-model:visible`  | 是否可见                     | `boolean`                | `true`            | -        | -                                                         |
| `v-model: collapsed`  | 左侧菜单折叠收起                    | `boolean`                | `true`           | -        | -                                                         |
| `mode`             | 左侧菜单模式，支持垂直和内嵌 | `'vertical' \| 'inline'` | `'vertical'` | -        | -                                                         |
| `headerDataSource` | 顶部菜单数据数组             | `MenuData[]`             | `[]`         | -        | 当使用`headerContent`插槽内置导航栏时生效，空数组不展示   |
| `headerActiveKey`  | 顶部菜单数据当前激活的菜单   | `VKey`                   | -            | -        | 当使用`headerContent`插槽内置导航栏时生效                 |
| `siderDataSource`  | 侧边菜单数据数组             | `MenuData[]`             | `[]`         | -        | 当使用`siderDataSource`插槽内置导航栏时生效，空数组不展示 |
| `siderActiveKey`   | 侧边菜单数据当前激活的菜单   | `VKey`                   | -            | -        | 当使用`headerContent`插槽内置导航栏时生效                 |
| `theme`            | 主题颜色                     | `'light' \| 'dark'`      | `'light'`    | -        | -                                                         |

### IxLayoutProSlot（导航组件插槽）

| 名称             | 说明                                                    | 参数类型          | 备注                                     |
| ---------------- | ------------------------------------------------------- | ----------------- | ---------------------------------------- |
| `headerLeft`     | 顶部区域左侧，适合放产品线logo和名字                    | -                 | 宽度按照规范，根据屏幕宽度限宽           |
| `headerContent`  | 顶部区域中间，适合放导航栏                              | -                 | 配置`headerDataSource`后默认展示导航栏                           |
| `headerMenuItem` | 导航元素，当使用`headerContent`插槽内置导航栏时可自定义 | -                 | -                                        |
| `headerRight`    | 顶部区域右侧，适合放登录状态、系统消息等                | -                 | 宽度按照规范，根据屏幕宽度限宽           |
| `siderTop`       | 侧边栏顶部，适合放模块标题和icon                        | -                 | -                                        |
| `siderContent`   | 侧边栏主体，适合放左树导航                              | -                 | 配置`siderDataSource`后 默认展示左树导航                         |
| `siderMenuItem`  | 导航元素，当使用`siderContent`插槽内置导航栏时可自定义  | -                 | -                                        |
| `siderBottom`    | 侧边栏底部，工具类插件                                  | -                 | 默认展开收起左树icon                     |
| `default`        | 页面主体                                                | `ContentSlotProp` | 加上左侧导航最小宽度1366px，再小横向滚动 |

### ContentSlotProp

| 名称               | 说明                   | 类型       | 备注 |
| ------------------ | ---------------------- | ---------- | ---- |
| `collapsed`        | 菜单收起状态           | `boolean`  | -    |
| `activeHeaderData` | 顶部导航栏激活的菜单项 | `MenuData` | -    |
| `activeSiderData`  | 左侧导航栏激活的菜单项 | `MenuData` | -    |

**Comment by coolyuantao** [comment]
还有一种混合导航的，`mode` 需要支持下

**Comment by danranVm** [comment]
| 名称 | 说明 | 类型 | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| `v-model:collapsed` | 是否收起菜单 | `boolean` | `false` | - | 仅对于侧边菜单生效 |
| `v-model:expandedKeys` | 当前展开菜单的 `key` 数组 | `VKey[]` | - | - | - |
| `v-model:selectedKeys` | 当前选中菜单的 `key` 数组 | `VKey[]` | - | - | - |
| `contentMode` | 内容模式 | `'fluid' \| 'fixed'` | `'fluid'` | - | - |
| `fixed` | 主题 | `boolean \| {sider: boolean, header: boolean}` | - | - | - |
| `logo` | 左上角 `logo` | `string \| #logo` | - | - | 传入 `url` 或插槽 |
| `menus` | 菜单数据 | `MenuData[]` | - | - | - |
| `mode` | 布局模式 | `'sider' \| 'header' \| 'mix1' \| 'mix2'` | `'sider'` | - | - |
| `siderProps` | 侧边栏配置 | `LayoutSiderProps` | `'sider'` | - | - |
| `theme` | 主题 | `light \| dark \| {sider: light \| dark, header: light \| dark}` | - | - | - |
| `title` | 左上角的标题 | `string \| #title` | - | - | - |
| `onMenuClick` | 点击菜单后的回调 | `(options: MenuClickOptions) => void>` | - | - | - |

**Comment by lo56ve** [comment]
## 最终讨论结果：

### IxProLayout

| 名称                 | 说明                     | 类型                                                         | 默认值                | 全局配置 | 备注                                                         |
| -------------------- | ------------------------ | ------------------------------------------------------------ | --------------------- | -------- | ------------------------------------------------------------ |
| `v-model: collapsed` | 左侧菜单折叠收起         | `boolean`                                                    | `false`               | -        | 仅对于侧边菜单生效                                           |
| `v-model:activeKey`  | 当前激活的菜单           | `VKey`                                                       | `menus`第一个叶子节点 | -        | -                                                            |
| `menus`              | 菜单数据                 | `MenuData[]`                                                 | `[]`                  | -        | 顶部的导航栏只展示第一层节点                                 |
| `mode`               | 布局模式                 | `'headerNav' \| 'siderNav' \| 'mixinSiderNav' \| 'mixinBothNav'` | `sider`               | -        | `headerNav`：只有顶部导航栏，不存在侧边栏<br />`siderNav`：只有侧边导航栏，不存在顶部导航栏<br />`mixinSiderNav`：同时存在顶部栏和侧边栏，导航栏只在侧边栏<br />`mixinBothNav`：同时存在顶部栏和侧边栏，导航栏在两边都存在，顶部导航栏只展示第一层节点 |
| `theme`              | 主题                     | `light \| dark \| {sider: light \| dark, header: light \| dark}` | `light`               | -        | -                                                            |
| `indent`             | 侧边导航栏的缩进         | `string \| number`                                           | `24`                  | -        | `string`支持带单位<br />不为`0`则导航栏展示为内嵌形式        |
| `breakpoint`         | 触发侧边栏折叠收起的断点 | `'xs' \| 'sm' \| 'md' \| 'lg' \| 'xl'`                       | -                     | -        | -                                                            |
| `onMenuClick`        | 点击菜单回调             | `(options: MenuClickOptions) => void>`                       | `() => {}`            | -        | -                                                            |
| `onCollapse`         | 菜单折叠收起的回调       | `(collapse: boolean) => void`                                | `() => {}`            | -        | -                                                            |

### IxProLayoutCollapse

左树展开收起按钮组件，不需要任何配置，按需放在对应位置即可

### IxProLayoutSlot

插槽

| 名称            | 说明                                     | 参数类型          | 备注                                                   |
| --------------- | ---------------------------------------- | ----------------- | ------------------------------------------------------ |
| `headerLogo`    | 顶部区域左侧，适合放产品线logo和名称     | -                 | 宽度按照视觉规范限宽，特殊需求覆盖less变量             |
| `headerContent` | 顶部区域中间，适合放导航栏               | -                 | 当`mode`为 `mixinBothNav \| headerNav`展示为顶部导航栏 |
| `headerEnd`     | 顶部区域右侧，适合放登录状态、系统消息等 | -                 | 宽度按照视觉规范限宽，特殊需求覆盖less变量             |
| `siderTop`      | 侧边栏顶部，适合放模块标题和icon         | -                 | -                                                      |
| `siderContent`  | 侧边栏主体，适合放左树导航               | -                 | 默认展示左树导航                                       |
| `siderBottom`   | 侧边栏底部，工具类插件，如折叠左树按钮   | -                 | -                                                      |
| `default`       | 页面主体                                 | `ContentSlotProp` | 加上左侧导航最小宽度1366px，再小横向滚动               |

### ContentSlotProp

| 名称         | 说明                 | 类型       | 备注 |
| ------------ | -------------------- | ---------- | ---- |
| `activeMenu` | 当前激活的菜单树分支 | `MenuData` | -    |
