### ISSUE TITLE
[comp:menu] vertical 情况下menu的selectKeys设置默认值时，IxMenuSub没有默认选中

### ISSUE THREAD

**Issue by typistZxd** [IDuxFE/idux#578]
### Steps to reproduce

```vue
<template>
  <IxMenu v-model:selectedKeys="selectedKeys" :dataSource="dataSource" style="width: 256px"></IxMenu>
</template>

<script setup lang="ts">
import { ref } from 'vue'
const selectedKeys = ref('item5')
const dataSource = [] // 复制示例数据即可
</script>
```

### What is expected?

默认设置选中值selectedKeys时，IxMenuSub也是选中状态

### What is actually happening?

默认设置选中值时，IxMenuSub没有选中，需要点击选中后才能展示选中状态

### Any additional comments? (optional)

![image](https://user-images.githubusercontent.com/17819018/144754351-8c61774f-c64d-4df3-b90c-11df41e6528d.png)

---
| Environment | Info |
|---|---|
| @idux |     |
| Browser |     |

**Comment by danranVm** [comment]
已修复。
