### ISSUE TITLE
[comp:modal] 增加关闭动画的 props

### ISSUE THREAD

**Issue by imguolao** [IDuxFE/idux#623]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

关闭弹窗的动画，因为在有些场景下需要关闭动画。

### What does the proposed API look like?

增加一个类型为 boolean 的 props 来控制。

**Comment by unknownzjc** [comment]
这个我来加一下。
