### ISSUE TITLE
[comp:IxSelect]  `options` 的 `value` 在使用 `null` 时，选择该选项无法正常显示

### ISSUE THREAD

**Issue by imguolao** [IDuxFE/idux#642]
### Reproduction link

无

### Steps to reproduce

`IxSelect` 的文档 api 描述 `options` 的 `value` 类型为 `any`，但在使用 `null` 时，选择该选项无法显示选中项。 

文档的 api 描述是否正常？

```vue
<template>
  <IxSelect :value.sync="value" :options="options"></IxSelect>
</template>
<script setup lang="ts">
import { ref } from '@idux/vue2-cdk/vue'
import { SelectOption } from '@idux/vue2-components/select'

const options: SelectOption[] = [
  { key: 1, label: 'Tom', value: 'tom' },
  { key: 2, label: 'empty', value: null },
]

const value = ref(null)
</script>
```

### What is actually happening?

显示正常

### Any additional comments? (optional)

显示不正常

---
| Environment | Info |
|---|---|
| @idux |     |
| Browser |     |

**Comment by danranVm** [comment]
修改下文档和类型定义吧，仅支持， string | number | object
