### ISSUE TITLE
[comp:all] prettier 设置了行末以 lf 结尾，但是众多文件却是以 CRLF 结尾

### ISSUE THREAD

**Issue by cisolarix** [IDuxFE/idux#651]
### What is expected?
希望能将二者保持一致

### What is actually happening?
![image](https://user-images.githubusercontent.com/1845040/147185122-ec08ad94-0e4c-4c1a-9b5e-1245a86d8f65.png)
![image](https://user-images.githubusercontent.com/1845040/147185151-b5f6c8cb-ac60-40cf-b232-010fbfd0849f.png)
![image](https://user-images.githubusercontent.com/1845040/147185169-8a95a3b3-3276-47f0-b5bf-98052c12541d.png)

### Any additional comments? (optional)

---
| Environment | Info |
|---|---|
| @idux |     |
| Browser |     |

**Comment by cisolarix** [comment]
@danranVm

**Comment by danranVm** [comment]
提交的时候会自动 fix 掉。
