### ISSUE TITLE
[cdk:portal] 当 `target` 为 `string`，没有使用 `querySelector` 查找 `dom`

### ISSUE THREAD

**Issue by imguolao** [IDuxFE/idux#654]
### Reproduction link

无

### Steps to reproduce

https://github.com/IDuxFE/idux/blob/e9f85e4a31216fbb1302054cde4ab5c51737cf8a/packages/cdk/portal/src/covertTarget.ts#L14-L31

当 `target` 为 `string`，应该使用 `querySelector` 去查找 `dom`，找到则插入到对应的 `dom` 中，未找到再插入 `body`。

### What is expected?

当 `target` 为 `string`，应该使用 `querySelector` 去查找 `dom`，找到则插入到对应的 `dom` 中，未找到再插入 `body`。

### What is actually happening?

当 `target` 为 `string`，会创建一个 `div` 为容器包裹，然后插入 `body`。

### Any additional comments? (optional)

---
| Environment | Info |
|---|---|
| @idux |     |
| Browser |     |

**Comment by LaamGinghong** [comment]
如果我没记错的话，string的时候返回的是portal的ID

**Comment by danranVm** [comment]
closed #656
