### ISSUE TITLE
[comp:drawer] 新增 `beforeOpen` 方法

### ISSUE THREAD

**Issue by imguolao** [IDuxFE/idux#663]
- [ ] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.

无

### What problem does this feature solve?

复用 `Drawer` 时，在打开抽屉之前修改 `Drawer` 的属性，防止闪烁。

现在在 `afterOpen` 修改属性会导致页面出现短暂的显示闪烁。

### What does the proposed API look like?

`beforeOpen` and `beforeClose`.

**Comment by danranVm** [comment]
同理，还有 modal 也要支持一下。
