### ISSUE TITLE
[comp: Timeline]feature Timeline component

### ISSUE THREAD

**Issue by sjia0307** [IduxFE/idux#69]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What does the proposed API look like?

**timeline**

| 属性 | 说明 | 类型  | 默认 |
| --- | --- | --- | --- |
| pending | 最后的幽灵节点是否存在，如果传入string或者slot，则默认存在，并且作为内容 | boolean \| string \| slot | false |
| pendingDot | 最后的幽灵节点存在时的时间轴点 | string \| slot | 加载中的icon |
| reverse | 时间节点是否倒叙 | boolean  | false |
| mode | 时间轴和内容的相对位置 | left \| alternate \| right  | right |

**slot**
| 方法 | 说明 | 
| --- | --- | 
| default | 时间节点 | 
| pending | 幽灵节点的内容 | 
| pendingDot | 幽灵节点的时间轴点 | 

**timeline-item**
| 属性 | 说明 | 类型  | 默认 |
| --- | --- | --- | --- |
| color | 圆圈颜色 | string | blue |
| dot | 自定义时间轴点 | string \| slot | - |
| position | 时间节点内容的位置，优先级比timeline的mode高 | left \| right | - |

**slot**
| 方法 | 说明 | 
| --- | --- | 
| default | timeline-item 的内容 | 
| dot | 自定义时间轴点 |

**Comment by danranVm** [comment]
@Pupils-web @danranVm 负责此组件的 review
