### ISSUE TITLE
[comp:stepper] stepper最后一步的标题宽度计算有问题，导致标题换行

### ISSUE THREAD

**Issue by sjia0307** [IDuxFE/idux#693]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://codesandbox.io/s/goofy-shockley-28bpk?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/goofy-shockley-28bpk?file=/src/components/HelloWorld.vue)

### Steps to reproduce
火狐浏览器打开包含步骤条的页面，最后一步的标题为两个字以上中文时，查看最后一步标题是否换行

### What is expected?
最后一步标题不换行

### What is actually happening?
最后一步标题换行了

### Environment Info 

```shell
Browsers:
    Firefox: 79.0
  npmPackages:
    @idux/cdk: 1.0.0-alpha.1 => 1.0.0-alpha.1 
    @idux/components: 1.0.0-alpha.2 => 1.0.0-alpha.2 
    @idux/pro: 1.0.0-alpha.1 => 1.0.0-alpha.1 
    vue: ^3.2.3 => 3.2.22
```

---
最后一步的ix-stepper-item-content，设置的宽度在火狐下跟其他浏览器有区别，去掉 8 px就正常了

**Comment by danranVm** [comment]
最新版本已修复。
