### ISSUE TITLE
[comp: collapse]  add collapse component

### ISSUE THREAD

**Issue by Usualminds** [IduxFE/idux#70]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

**Comment by danranVm** [comment]
@coolyuantao @danranVm 负责此组件的 review， API 设计完成后请 @ 他们

**Comment by Usualminds** [comment]
### ix-collapse

#### Props

|名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| :--- | :--- | :--- |  :--- |  :--- |  :--- |
| `accordion` | 是否开启手风琴模式 | `boolean` | `false` | - | 只能展开一个 tab |
| `activeName(v-model)` | 当前激活面板对应的 name | `string[] \| string` | - | - |- |
| `borderless` | 是否显示边框 | `boolean` | `true` | - |- |


#### Events

| 名称 | 说明 | 参数类型 | 备注 |
|  :--- |  :--- |  :--- |  :--- |
| `change` | 激活面板时触发 | `function` | 参数 `activeName` |


### ix-collapse-item

#### Props

| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| :--- |  :--- |  :--- |  :--- |  :--- | --- |
| `name` | 唯一标识符 | `string` | - | - | - |
| `title` | 折叠面板标题 | `string` | - | - | - |
| `disabled` | 是否禁用该面板 | `boolean` | `false` | - | - |
| `icon` | 自定义左侧图标 | `string` | - | - |- |

#### Slots

| 名称 | 说明 | 类型  | 默认值 | 备注 |
|  :--- |  :--- |  :--- |  :--- |  :--- | 
| `default` | 面板内容 | - | - | - |

**Comment by danranVm** [comment]
- `collapse `
  - `accordion` 和 `borderless ` 支持一下全局配置？另外`borderless` 的默认值应该是 false 吧 
  - `change` 这个事件，周一跟大家在讨论下，是否需要提供。
  - `v-model:activeName` 是在 `item` 配置了  `name` 的情况下才生效吧，手风琴模式下为 `string`, 其他情况为 `string[]`, 这个需要在备注中说明。
- `collapse-item`
  - `icon`支持全局配置
  - 应该需要添加一个 `showIcon` 的配置？支持全局配置
  - 同时支持 `v-model:active`

**Comment by Usualminds** [comment]
> * `collapse `
>   
>   * `accordion` 和 `borderless ` 支持一下全局配置？另外`borderless` 的默认值应该是 false 吧
>   * `change` 这个事件，周一跟大家在讨论下，是否需要提供。
>   * `v-model:activeName` 是在 `item` 配置了  `name` 的情况下才生效吧，手风琴模式下为 `string`, 其他情况为 `string[]`, 这个需要在备注中说明。
> * `collapse-item`
>   
>   * `icon` 支持全局配置, 还需要支持 `slot`
>   * 应该需要添加一个 `showIcon` 的配置？支持全局配置
>   * `title` 支持 `slot`
>   * 同时支持 `v-model:active`


#### `collapse`
- `accordion` 和 `borderless ` 支持全局配置，默认值为 false
- 支持 `change`
- 已修改

#### `collapse-item`
- `icon`支持 `slot`
- 这里 `icon` 传空就不显示，可以组件内部处理
-  `title` 支持 `slot`
-  这里似乎没有必要支持 `v-model:active` ? 展开项可通过 `collapse ` 中 `activeName(v-model)` 指定
