### ISSUE TITLE
[comp:collapse] 新增IxCollapsePanel之间间距和自定义展开图标位置功能

### ISSUE THREAD

**Issue by typistZxd** [IDuxFE/idux#731]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
## What problem does this feature solve?
1. gap：IxCollapsePanel之间的间距
2. expandIconPlacement：自定义展开图标位置

## What does the proposed API look like?
| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| `expandIconPlacement` | 自定义展开图标位置 | `'start' \| 'end'` | `'start'` | ✅ |- |
| `gap` | `IxCollapsePanel`之间的间距 | `number` | `8` | ✅ | - |

**Comment by danranVm** [comment]
gap 可以加，expandIconPlacement 应该没必要吧。
按照视觉规范改吧，如果有疑问，可以拉上我一起跟视觉讨论下。

**Comment by danranVm** [comment]
已经按照最新的设计规范修改了样式。
