### ISSUE TITLE
[comp:select] select多选的时候，展示会撑开高度多行展示

### ISSUE THREAD

**Issue by threedayAAAAA** [IDuxFE/idux#756]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://codesandbox.io/s/unruffled-forest-fb0fbi?file=/src/Demo.vue](https://codesandbox.io/s/unruffled-forest-fb0fbi?file=/src/Demo.vue)

### Steps to reproduce
下拉选择框勾选多个，查看展示

### What is expected?
select勾选多个的时候正常展示，不要撑开高度以多行的形式展示，一行展示即可，超过宽度则滚动或者省略展示

### What is actually happening?
勾选多个的时候会撑开select，以多行的形式展示

### Environment Info 

```shell
 Browsers:
    Chrome: 98.0.4758.82


```

**Comment by danranVm** [comment]
@hangboss1761

**Comment by danranVm** [comment]
可以使用 maxLabelCount + 自定义插槽解决。
参见：https://idux.site/components/select/zh#components-select-demo-CustomLabel
