### ISSUE TITLE
[comp:table] 表格实现撑满页面时，内容区自动计算高度进行滚动

### ISSUE THREAD

**Issue by MiumMi** [IDuxFE/idux#757]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
## What problem does this feature solve?
表格内容区能实现自动计算高度进行滚动

## What does the proposed API look like?
scorll.height当是整个表格的高度设定，然后内容区自动减去表头、分页高度自动计算高度进行滚动。height接收100%和px的两种设定

**Comment by danranVm** [comment]
@MiumMi 需要更详细的需求描述，和使用场景。
