### ISSUE TITLE
[comp:popover] ppopover组件trigger为 hover, focus,  manual 等形式时  点击其他地方未自动隐藏 

### ISSUE THREAD

**Issue by threedayAAAAA** [IDuxFE/idux#765]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://codesandbox.io/s/shy-darkness-ryr6zd?file=/src/Demo.vue](https://codesandbox.io/s/shy-darkness-ryr6zd?file=/src/Demo.vue)

### Steps to reproduce
1.两个按钮，一个是popover卡片，一个点击弹出弹窗
2. popover展示，然后点击另一个按钮
3. 弹出弹窗
4. popover没有隐藏

### What is expected?
点击其他地方时   popover自动隐藏

### What is actually happening?
点击其他地方时   popover未隐藏

### Environment Info 

```shell
"@idux/components": "^1.0.0-alpha.6"
```

**Comment by danranVm** [comment]
我猜测是 clickOutside 指令的 bug, 可以排查一下，点击其他地方时，有没有触发回调。
