### ISSUE TITLE
[comp:table] table配置scorll.width无效

### ISSUE THREAD

**Issue by threedayAAAAA** [IDuxFE/idux#766]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://codesandbox.io/s/heuristic-nova-7hvq51?file=/src/Demo.vue](https://codesandbox.io/s/heuristic-nova-7hvq51?file=/src/Demo.vue)

### Steps to reproduce
table配置scorll.width无效 会默认撑满父元素

### What is expected?
table配置scorll.width 效果正常

### What is actually happening?
会默认撑满父元素

### Environment Info 

```shell
"@idux/cdk": "^1.0.0-alpha.6",
    "@idux/components": "^1.0.0-alpha.6",
    "@idux/pro": "^1.0.0-alpha.6",
```

**Comment by danranVm** [comment]
这个组件就是这么设计的，会给 table 加上一个 `min-width: 100%`  的样式。
你可以给父元素指定宽度，或者直接给 `IxTable` 设置宽度都是可以实现横向滚动条的。
