### ISSUE TITLE
[comp:tabs] tabs 组件less变量问题

### ISSUE THREAD

**Issue by threedayAAAAA** [IDuxFE/idux#768]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
## What problem does this feature solve?
定制化的配置  tabs 组件的 active时的部分样式

## What does the proposed API look like?
@tabs-active-fontSize

**Comment by danranVm** [comment]
新增一个变量吧。

**Comment by danranVm** [comment]
刚刚尝试了一下，感觉这并不是一个好的设计，你们确定要这么做吗？
