### ISSUE TITLE
[pro:layout] pro-layout组件less变量问题

### ISSUE THREAD

**Issue by threedayAAAAA** [IDuxFE/idux#770]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://codesandbox.io/s/ystxd3](https://codesandbox.io/s/ystxd3)

### Steps to reproduce
less变量覆盖
@pro-layout-light-background-color 
@background-color-component 
@pro-layout-header-height 
不生效

### What is expected?
配置 @pro-layout-light-background-color @background-color-component @pro-layout-header-height 生效

### What is actually happening?
配置 @pro-layout-light-background-color @background-color-component @pro-layout-header-height 不生效

### Environment Info 

```shell
"@idux/cdk": "^1.0.0-alpha.6",
    "@idux/components": "^1.0.0-alpha.6",
    "@idux/pro": "^1.0.0-alpha.6",
```

---
怀疑该组件其他变量也有该问题可以一起看下

**Comment by danranVm** [comment]
检查一下有没有正确引入 `pro` 的 less 文件？
其他变量可以被覆盖吗？
