### ISSUE TITLE
[comp:input] 输入框的less变量问题

### ISSUE THREAD

**Issue by threedayAAAAA** [IDuxFE/idux#776]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
## What problem does this feature solve?
1. input的less变量并未在文档中体现希望下个版本的文档能给出相关变量
2. @input-height-md 配置后 input组件的高度并未生效

## What does the proposed API look like?
1.文档能给出input组件的相关less变量
2. @input-height-md 配置后 input组件的高度能生效

**Comment by danranVm** [comment]
@threedayAAAAA 文档中已经给出来了相关变量，麻烦再试一下覆盖高度呢？
建议直接覆盖 @form-height-md, 因为所以的表单输入框都公用这个变量。

**Comment by danranVm** [comment]
re #783
