### ISSUE TITLE
[other:*] 所有 less 变量相关的问题汇总

### ISSUE THREAD

**Issue by danranVm** [IDuxFE/idux#783]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
## What problem does this feature solve?
- less 变量未生效
- less 变量缺失

## What does the proposed API look like?
都统一在这个  issue 中汇总。

**Comment by threedayAAAAA** [comment]
希望tabs能提供一个 @tabs-nav-font-weight

**Comment by danranVm** [comment]
> 希望tabs能提供一个 @tabs-nav-font-weight

昨天我跟设计是还聊过这个组件，好像没有说要修改 font-weight 吧。
