### ISSUE TITLE
[comp:menu] menu组件不应该将click事件阻止冒泡

### ISSUE THREAD

**Issue by threedayAAAAA** [IDuxFE/idux#791]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://codesandbox.io/s/oriqbn](https://codesandbox.io/s/oriqbn)

### Steps to reproduce
无

### What is expected?
menu组件不应该将click事件阻止冒泡

### What is actually happening?
menu组件将click事件阻止冒泡

### Environment Info 

```shell
v1.0.0-beta.0
```

**Comment by danranVm** [comment]
dup #765
