### ISSUE TITLE
[comp:menu] menu组件在 关闭后 依然保持了之前被选中项的样式

### ISSUE THREAD

**Issue by threedayAAAAA** [IDuxFE/idux#793]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://codesandbox.io/s/oriqbn](https://codesandbox.io/s/oriqbn)

### Steps to reproduce
1. 选中菜单的某一项
2. 将菜单收起
3. 展开菜单，之前被选中的项依然被标蓝

### What is expected?
之前被选中的项不被标蓝

### What is actually happening?
之前被选中的项依然被标蓝

### Environment Info 

```shell
v1.0.0-beta.0
```

**Comment by danranVm** [comment]
可以通过 `:selectable="false"` 解决
