### ISSUE TITLE
[comp:slider] 当可调整范围较小时，点击和拖拽都无法修改值

### ISSUE THREAD

**Issue by danranVm** [IDuxFE/idux#817]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://codesandbox.io/s/cool-buck-hzlgff?file=/src/Demo.vue](https://codesandbox.io/s/cool-buck-hzlgff?file=/src/Demo.vue)

### Steps to reproduce
无论是点击还是拖动，都有明显异常。

### What is expected?
可以通过点击或者拖拽来调整值

### What is actually happening?
点击和拖动，都无法调整值

### Environment Info 

```shell
  Browsers:
    Edge: 99.0.1150.46
  npmPackages:
    @idux/cdk: latest => 1.0.0-beta.2
    @idux/components: latest => 1.0.0-beta.2
    @idux/pro: latest => 1.0.0-beta.2
    vue: next => 3.2.31
```

---
个人猜测是可调整范围较小导致的

**Comment by imguolao** [comment]
`min` 不是从 0 开始导致的，我猜是计算距离的时候没有用 `props.max + props.min`，而是直接用 `props.max`，导致少计算了 `200`  的距离。

**Comment by imguolao** [comment]
计算距离也没有考虑到 `min`,  `max` 为 `正 \| 负` 的问题
