### ISSUE TITLE
[comp:tag] 新增 tag group 组件

### ISSUE THREAD

**Issue by danranVm** [IDuxFE/idux#826]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
## What problem does this feature solve?
常用于表格的筛选功能。

### TagGroupProps

| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| `v-model:activeKeys` | 激活的标签的 key | `VKey[]` | `close` | - | - |
| `clickable` | 标签是否可点击 | `string \| #closeIcon` | `close` | - | - |
| `closable` | 标签是否可关闭 | `boolean` | `false` | - |- |
| `closeIcon` | 标签是否可关闭 | `string \| #closeIcon` | `close` | - | - |
| `dataSource` | 数据源 | `TagData[]` | - | - | - |
| `shape` | 标签形状 | `'round' \| 'rect'` | - | - | - |
| `onClick` | 标签被点击 | `(key:VKey, evt: MouseEvent) => void` | - | - | - |
| `onClose` | 标签的关闭图标被点击 | `(key:VKey, evt: MouseEvent) => void` | - | - | - |

**Comment by danranVm** [comment]
容器使用 flex 布局，新增两个 props:
- gap: 每个标签的间隔，默认值给个 8，
- wrap: 是否自动换行，默认是为 true,

**Comment by brenner8023** [comment]
@brenner8023
