### ISSUE TITLE
[other:*] 测试框架迁移至 vitest

### ISSUE THREAD

**Issue by danranVm** [IDuxFE/idux#828]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
## What problem does this feature solve?
更好的与 vite 相结合。

## What does the proposed API look like?
参考：https://cn.vitest.dev/guide/migration.html

**Comment by Jouryjc** [comment]
@Jouryjc
