### ISSUE TITLE
[comp:tag] 未处理极端场景下的展示

### ISSUE THREAD

**Issue by brenner8023** [IDuxFE/idux#841]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[复现链接](https://brenner8023.github.io/idux-playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwicGFkZGluZzogMjBweCAxMDBweDtcIj5cbiAgICA8ZGl2PlxuICAgICAgPEl4VGFnIDpudW1iZXI9XCIzMDAwMDAwXCI+5L2O5Y2xPC9JeFRhZz5cbiAgICAgIDxJeFRhZyBjb2xvcj1cIiNmYTcyMWJcIiA6bnVtYmVyPVwiNFwiPuS4reWNsTwvSXhUYWc+XG4gICAgICA8SXhUYWcgY29sb3I9XCIjY2YxNzFkXCIgOm51bWJlcj1cIjcwMDAwMFwiPumrmOWNsTwvSXhUYWc+XG4gICAgICA8SXhUYWcgY29sb3I9XCIjODIwMTBlXCIgOm51bWJlcj1cIjk5OTlcIj7lt7LlpLHpmbc8L0l4VGFnPlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBzZXR1cElkdXggfSBmcm9tICcuL3NldHVwSWR1eC5qcydcblxuc2V0dXBJZHV4KCkgLy8gZG9uJ3QgcmVtb3ZlXG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCIuL3Z1ZS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiaWR1eFwiOiBcIi4vaWR1eC5qc1wiXG4gIH1cbn0ifQ==)

### Steps to reproduce
```
<IxTag :number="300000000000">低危</IxTag>
```

![image](https://user-images.githubusercontent.com/31237954/162230141-9cb6e2df-3ba6-411b-aea2-bc45766c0a45.png)

### What is expected?
大数场景能够有一个合理的展示，而不是溢出，很难看

### What is actually happening?
大数场景下展示溢出了

### Environment Info 

```shell
Vue@3.2.31, Idux@1.0.0-beta.2
```

**Comment by danranVm** [comment]
一般来说风险等级都不会超过 99 吧，不过这个地方可以参考 `badge` 优化一下。
超出 `9` 的显示 `9+` ？

**Comment by sallerli1** [comment]
收到，排到下周一改
