### ISSUE TITLE
[comp:anchor] anchor 组件使用 v-show时组件宽高计算有误

### ISSUE THREAD

**Issue by threedayAAAAA** [IDuxFE/idux#849]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://codesandbox.io/s/romantic-black-73r6wm?file=/src/App.vue](https://codesandbox.io/s/romantic-black-73r6wm?file=/src/App.vue)

### Steps to reproduce
见重现连接

### What is expected?
1. anchor 组件使用 v-show时组件宽高计算正常
2. 使用v-if时位置计算正常

### What is actually happening?
1. anchor 组件使用 v-show时组件宽高计算有误
2. 使用v-if时只有页面重绘才会计算位置

### Environment Info 

```shell
见重现连接
```

**Comment by danranVm** [comment]
@jackson-yyy 同时也看看 v-if 的情况
