### ISSUE TITLE
[site:*] 底部的常见问题和更新日志无法跳转

### ISSUE THREAD

**Issue by hawtim** [IDuxFE/idux#876]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://github.com/IDuxFE/idux](https://github.com/IDuxFE/idux)

### Steps to reproduce
点击网站底部常见问题和更新日志链接

### What is expected?
能正确跳转到正确的路径

### What is actually happening?
不能跳转到 changelog 和 faq

### Environment Info 

```shell
empty
```

**Comment by hawtim** [comment]
you can assign this issue to me if necessary

**Comment by danranVm** [comment]
closed #1219
