### ISSUE TITLE
[comp:select] select 的label-key 为 value时, v-model的值异常

### ISSUE THREAD

**Issue by threedayAAAAA** [IDuxFE/idux#890]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://codesandbox.io/s/festive-christian-9qw56j?file=/src/Demo.vue](https://codesandbox.io/s/festive-christian-9qw56j?file=/src/Demo.vue)

### Steps to reproduce
见复现连接

### What is expected?
label-key 为 value时, v-model的值正常

### What is actually happening?
label-key 为 value时, v-model的值异常

### Environment Info 

```shell
"@idux/cdk": "^1.0.0-beta.8",
    "@idux/components": "^1.0.0-beta.8",
    "@idux/pro": "^1.0.0-beta.8",
```

**Comment by danranVm** [comment]
closed #892
