### ISSUE TITLE
[pro:transfer] 期望@idux/pro不引用@idux/components/_private的东西

### ISSUE THREAD

**Issue by brenner8023** [IDuxFE/idux#894]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://github.com/IDuxFE/idux](https://github.com/IDuxFE/idux)

### Steps to reproduce
打开idux仓库，查看packages/pro/transfer的源码

### What is expected?
没有引用@idux/components/_private的东西

### What is actually happening?
存在引用`@idux/components/_private`的文件

```
packages/pro/transfer/src/ProTransfer.tsx
packages/pro/transfer/src/token.ts
packages/pro/transfer/src/content/ProTransferList.tsx
packages/pro/transfer/src/content/ProTransferTable.tsx
packages/pro/transfer/src/content/ProTransferTree.tsx
```

![image](https://user-images.githubusercontent.com/31237954/167324215-958ff83f-ecf4-4294-a492-9cd3b98633bf.png)

### Environment Info 

```shell
Browsers:
    Internet Explorer: 11.0.18362.1
```

**Comment by danranVm** [comment]
@sallerli1 是不是可以把 ChechableList 移动到 transfer 目录里？然后 export 出去给 Pro 用。
