### ISSUE TITLE
[comp:tooltip] 当popover内是禁用的button时无法展示提示

### ISSUE THREAD

**Issue by brenner8023** [IDuxFE/idux#906]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[复现链接](https://brenner8023.github.io/idux-playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwicGFkZGluZzogMjBweCAxMDBweDtcIj5cbiAgICA8SXhQb3BvdmVyIGhlYWRlcj1cIlRpdGxlXCIgY29udGVudD1cInRlc3RcIj5cbiAgICAgIDxzcGFuPlxuICAgICAgXHQ8SXhCdXR0b24gOmRpc2FibGVkPVwidHJ1ZVwiPkhvdmVyPC9JeEJ1dHRvbj5cbiAgICAgIDwvc3Bhbj5cbiAgICA8L0l4UG9wb3Zlcj5cbiAgPC9kaXYXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgc2V0dXBJZHV4IH0gZnJvbSAnLi9zZXR1cElkdXguanMnXG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcyMDA4Jylcblxuc2V0dXBJZHV4KCkgLy8gZG9uJ3QgcmVtb3ZlXG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCIuL3Z1ZS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiaWR1eFwiOiBcIi4vaWR1eC5qc1wiXG4gIH1cbn0ifQ==)

### Steps to reproduce
```
<IxPopover header="Title" content="test">
      <span>
      	<IxButton :disabled="true">Hover</IxButton>
      </span>
    </IxPopover>
```

### What is expected?
期望有配置的提示

### What is actually happening?
没有提示

### Environment Info 

```shell
Vue@3.2.31, Idux@1.0.0-beta.2
```

**Comment by brenner8023** [comment]
popver使用嵌套的时候，外层是click打开，内层是hover打开，点击的时候，外层popver打开失败，但是在中间加一个元素可以，[复现链接](https://brenner8023.github.io/idux-playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwicGFkZGluZzogMjBweCAxMDBweDtcIj5cbiAgICA8SXhQb3BvdmVyIHRyaWdnZXI9XCJjbGlja1wiIGhlYWRlcj1cIlRpdGxlXCIgY29udGVudD1cImNsaWNrXCI+XG4gICAgICA8ZGl2PlxuICAgICAgICA8SXhQb3BvdmVyIGhlYWRlcj1cIlRpdGxlXCIgY29udGVudD1cImhvdmVyXCI+XG4gICAgICAgICAgICA8SXhCdXR0b24+5oyJ6ZKuPC9JeEJ1dHRvbj5cbiAgICAgICAgPC9JeFBvcG92ZXI+XG4gICAgICA8L2Rpdj5cbiAgICA8L0l4UG9wb3Zlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgc2V0dXBJZHV4IH0gZnJvbSAnLi9zZXR1cElkdXguanMnXG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcyMDA4Jylcblxuc2V0dXBJZHV4KCkgLy8gZG9uJ3QgcmVtb3ZlXG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCIuL3Z1ZS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiaWR1eFwiOiBcIi4vaWR1eC5qc1wiXG4gIH1cbn0ifQ==)

**Comment by danranVm** [comment]
在文档里加个 FAQ 说明一下？
