### ISSUE TITLE
[comp: anchor] add anchor component

### ISSUE THREAD

**Issue by bunnybunny3** [IduxFE/idux#93]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用于跳转到页面指定位置。

### What does the proposed API look like?

- 可设置是否是固定模式。即是否将其固定在可视范围
- 可设置固定模式下是否显示小圆点
- 可指定滚动容器，默认window
- 可设置距离窗口顶部达到指定偏移量（offsetTop）后触发其高亮
- 可设置锚点滚动偏移量，默认同offsetTop

## 例子
```js
<ix-anchor>
    <ix-link href="#example" title="example" />
    <ix-link href="#api" title="api">
      <ix-link href="#props" title="props" />
      <ix-link href="#emit" title="emit" />
    </ix-link>
 </ix-anchor>
```
#### Props

| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| `affix` | 是否是固定模式 | boolean | `true`  | - | - |
| `showInkInFixed` | 固定模式是否显示小圆点 | boolean | `false` | ✅ | - |
| `target ` | 指定滚动的容器 | string\|HTMLElement | `window` | - | - |
| `offsetTop` | 距离窗口顶部达到指定偏移量后触发激活 | number | - | - | - |
| `targetOffset` | 锚点滚动偏移量，默认与 offsetTop 相同 | number | - | - | - |

#### Emits

| 名称 | 说明 | 参数  |
| --- | --- | --- | 
| `click` | 锚点元素点击事件| `e: Event, link: Object` |
| `change` | 监听锚点链接改变 | `activeLink: string` |

#### Props
> 除以下表格外还支持原生 `a` 元素的[所有属性](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/a)。

| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| `href` | 锚点链接 | `string` | - | - | - |
| `title` | 文字内容 | `string` | - | - | - |

**Comment by danranVm** [comment]
@Pupils-web @Pupils-web 负责此组件的 review， API 设计完成后请 `@` 他们

**Comment by bunnybunny3** [comment]
@danranVm @Pupils-web 麻烦review 下 api

**Comment by danranVm** [comment]
- ix-anchor
  - container 改成 target 吧，和 BackTop 和 Affix 组件保持一致，你也可以参考一下这两个组件的代码，有封装好的工具函数
- ix-anchor-link 改成 ix-link 吧
  - 然后实现可以用 `a` 元素实现
  - 文档中不需要写 target ，只要声明一句：**除以下表格之外还支持原生 `a` 元素的[所有属性](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/a)**

**Comment by Pupils-web** [comment]
我没有问题

**Comment by bunnybunny3** [comment]
@danranVm 已更新api

**Comment by danranVm** [comment]
#279
