### ISSUE TITLE
[comp: Skeleton] add Skeleton component

### ISSUE THREAD

**Issue by Pupils-web** [IduxFE/idux#94]
- [ ] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在需要等待加载内容的位置提供一个占位图形组合。

- 适用于图文列表信息比较多的场景
- 可以被 Spin 完全代替，但是在可用的场景下可以比 Spin 提供更好的视觉效果和用户体验。
- 提供预设模板，自由组合

#### `Props`

名称 | 说明 | 类型 | 默认值 | 全局配置 | 备注
-- | -- | -- | -- | -- | --
`animation` | 是否展示动画效果 | `boolean` | `false`| - | -
`width` | 设置组件宽度 | `number` \|  `string` | `100%` | - | -
`height` | 设置组件高度 | `number`\| `string` | `100%` | - | -
`loading` | 是否开启占位图 | `boolean` | `false` | - | `false`的值只有在 `default` 槽中有内容时才会工作。
`type` | 字符串分隔要创建的骨架组件列表 | `string` | `undefined` | - | `required`骨架组件列表，例如 `type="text@3"` 和 `type="card`, `list-item`"。将根据提供的字符串递归生成相应的框架。 还支持多个元素的简写，例如 `article@3`和 `paragraph@2` ，它们将生成 `3 article skeletons and 2 paragraph` 骨架。具体的预设列表会根据后续具体业务场景来建立。
`types` | 将与预定义选项结合使用的自定义类型对象。 有关可用的预定义选项的列表 | `object` | `{}` | - | 与`type`搭配使用，建立自定义的骨架模板。

名称 | 说明
-- | --
`default` | 默认插槽，放置骨架屏子组件

**Comment by danranVm** [comment]
@zymoplastic @danranVm 负责此组件的 review， API 设计完成后请 `@` 他们

**Comment by Pupils-web** [comment]
@danranVm @zymoplastic 麻烦大佬review一下

**Comment by danranVm** [comment]
和 antd 的设计差别优点大，能写一两个使用 demo 看看嘛？

**Comment by zymoplastic** [comment]
`type` 感觉有点像制造一些小的 DSL 了, 能不能详细说下需求, 如果需求不够的话能不能考虑使用其他办法解决, 因为自建 DSL 可能带来一些学习成本和阅读障碍问题, 需要有合适的场景.

目前来看 `type` 的字符串的用处目前我看到只有提供 `skeleton item` 组合和个数两种用途, 而格式简单分析如下:
```text
var: [a-zA-Z\_\$]+[0-9a-zA-Z\_\$]*
item: 
     `(var)@(\d)`,
     var

itemList:
     item,
     `(item)+(item)...`  // 没看到有说符号, 假设是 +, 不写

type: itemList           // type 属性接受的字符串定义
```
首先, 给 item 传参放到了一个新的属性 `types` 上面, 这就变成了两张皮了, 好奇怎么知道是给哪一个 item 传值, 难道是指定第 n 个 item?
其次, 目前的功能完全可以只放到 `types` 里面,增加 name 和 length 的属性即可, 也就是说 JSON/JSON-Schema 的表达能力完全足够了.

**Comment by Pupils-web** [comment]
> `type` 感觉有点像制造一些小的 DSL 了, 能不能详细说下需求, 如果需求不够的话能不能考虑使用其他办法解决, 因为自建 DSL 可能带来一些学习成本和阅读障碍问题, 需要有合适的场景.
> 
> 目前来看 `type` 的字符串的用处目前我看到只有提供 `skeleton item` 组合和个数两种用途, 而格式简单分析如下:
> 
> ```
> var: [a-zA-Z\_\$][0-9a-zA-Z\_\$]*
> item: 
>      `(var)@(\d)`,
>      var
> 
> itemList:
>      item,
>      `(item)+(item)...`  // 没看到有说符号, 假设是 +
> 
> type: itemList           // type 属性接受的字符串定义
> ```
> 
> 首先, 给 item 传参放到了一个新的属性 `types` 上面, 这就变成了两张皮了, 好奇怎么知道是给哪一个 item 传值, 难道是指定第 n 个 item?
> 其次, 目前的功能完全可以只放到 `types` 里面,增加 name 和 length 的属性即可, 也就是说 JSON/JSON-Schema 的表达能力完全足够了.

`types`可以改为`json`格式， 降低dsl带来的学习成本，方案的话用这种模板搭积木的方式ok不？@danranVm 你觉着如何

**Comment by zymoplastic** [comment]
`type` 和 `types` 能不能单独拆出来作为 pro 提供, 基础组件的还是像 antd 一样提供功能?

**Comment by Pupils-web** [comment]
最终方案：

1. 采用搭积木的方式，单元组件提供上述 `api` 除 `types` 外的全部功能。
2. `types`额外提供预设模板的功能放到`pro`中实现。
3. `types`采用配置项形式注入模板。

`DEMO`
```<ix-skeleton type="card"></ix-skeleton>```
```<ix-skeleton-pro type="custom" types="{custom: [name: '', length: 2']}"></ix-skeleton-pro>```

```
Type SkeletonType = 'card' | 'avator' | 'list-item';

Interface Types {
  [key: string]: {name: SkeletonType, length: number}[];
}
```

**Comment by danranVm** [comment]
> 最终方案：
> 
> 1. 采用搭积木的方式，单元组件提供上述 `api` 除 `types` 外的全部功能。
> 2. `types`额外提供预设模板的功能放到`pro`中实现。
> 3. `types`采用配置项形式注入模板。
> 
> `DEMO`
> 
> ```
> <ix-skeleton type="card"></ix-skeleton>
> <ix-skeleton-pro type="custom" types="{custom: [name: 'card', length: 2']}"></ix-skeleton-pro>
> 
> Type SkeletonType = 'card' | 'avator' | 'list-item';
> 
> Interface Types {
>   [key: string]: {name: SkeletonType, length: number}[];
> }
> ```

那就按照这个来吧。

**Comment by zymoplastic** [comment]
我没问题了

**Comment by Pupils-web** [comment]
重新设计Skeleton组件，这个issue关闭
