### ISSUE TITLE
[cdk:forms] slider的control不生效

### ISSUE THREAD

**Issue by Yummy-zZ** [IDuxFE/idux#942]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://codesandbox.io/s/idux-starter-7o9lv?file=/src/App.vue](https://codesandbox.io/s/idux-starter-7o9lv?file=/src/App.vue)

### Steps to reproduce
1.<ix-form><ix-form-item><ix-slider control="xx"></ix-form-item></ix-form>
2.const formGroup = useFormGroup({
    xx: [10, required],
});
3.slider依然是0，而且滑不动

### What is expected?
slider有10，而且能滑动

### What is actually happening?
0，滑不动

### Environment Info 

```shell
Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.50)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @idux/cdk: ^1.0.0-beta.12 => 1.0.0-beta.12
    @idux/components: ^1.0.0-beta.12 => 1.0.0-beta.12
    @idux/pro: ^1.0.0-beta.12 => 1.0.0-beta.12
    vue: ^3.2.31 => 3.2.31
```

**Comment by imguolao** [comment]
这个不是 bug，是不知道为什么当初 api 审核分了两个事件：input 和 change，需要两个一起用才能正常。
