### ISSUE TITLE
[cdk:portal] 微前端场景下可能会有问题，出现弹窗打不开

### ISSUE THREAD

**Issue by brenner8023** [IDuxFE/idux#949]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://github.com/IDuxFE/idux-playground](https://github.com/IDuxFE/idux-playground)

### Steps to reproduce
idux-playground中已经有一段弹窗代码，
点击打开弹窗，此时弹窗能够正常打开。
在playground中进行编辑，右侧iframe更新后，再次点击，弹窗打不开。
```
<template>
  <div style="padding: 24px">
    <IxButton @click="onOpen">Open modal11223344</IxButton>
  </div>
</template>

<script setup lang="ts">
import { useModal } from '@idux/components'

const { open } = useModal()
const onOpen = () => open({ header: 'Hello @idux', content: 'This is playground app' })
</script>
```

### What is expected?
idux-playground中已经有一段弹窗代码，
点击打开弹窗，此时弹窗能够正常打开。
在playground中进行编辑，右侧iframe更新后，再次点击，弹窗可以打开。

### What is actually happening?
第一次可以打开，在playground中进行编辑，右侧iframe更新后，再次点击，弹窗打不开。

### Environment Info 

```shell
```
Browsers:
    Chrome: 101.0.4951.54
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.33)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vue: ^3.2.33 => 3.2.31 
```
```

---
1. 原因应该是代码编辑导致iframe重新刷新，这时ix-modal-container的dom被销毁，但是cdk/portal/src/convertTarget.ts里面的targetHashmap未清除。导致逻辑有问题，弹窗打不开。
2. 本质上是dom被销毁，导致targetHashmap保存的值与真实dom对应不上的问题。
3. 普通场景下，该问题一般不会出现，在微前端场景，该问题可能会碰到。

**Comment by brenner8023** [comment]
代码截图：

![image](https://user-images.githubusercontent.com/31237954/173084602-341a370e-9665-4404-a0ab-bea1a365dfb4.png)

![image](https://user-images.githubusercontent.com/31237954/173084890-ec36256b-5962-4e7d-a40c-693b797b5f60.png)

**Comment by brenner8023** [comment]
https://github.com/IDuxFE/idux-playground/commit/e97f4673ec7121eb8bcc44ed1f723f84b3141291

**Comment by danranVm** [comment]
是不是直接把 `targetHashmap` 干掉算了？

**Comment by brenner8023** [comment]
https://github.com/brenner8023/idux/blob/ddd67e3284b6575701e642da5e359f9c4e58431e/packages/cdk/portal/src/convertTarget.ts#L25-L30

这段代码还有个问题就是`querySelector(temp)`传的是temp，下面`element.classList.add(temp)`传的是也是temp，是个bug，因为传参一个需要字符串带点，另一个不需要带点。
