### ISSUE TITLE
[comp: Statistic]

### ISSUE THREAD

**Issue by clfeng** [IduxFE/idux#95]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

展示统计数值。

### What does the proposed API look like?

| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| formatter        | 自定义数值展示   | v-slot \| (value) => string | -      |||
| precision        | 数值精度         | number                          | -      |✅||
| prefix           | 设置数值的前缀   | string \| v-slot                | -      |||
| suffix           | 设置数值的后缀   | string \| v-slot                | -      |||
| title            | 数值的标题       | string \| v-slot                | -      |||
| value            | 数值内容         | string \| number                | -      |||

**Comment by danranVm** [comment]
@Usualminds @danranVm 负责此组件的 review， API 设计完成后请 `@` 他们

**Comment by danranVm** [comment]
- decimalSeparator 和 groupSeparator，感觉意义不大？毕竟已经有 formatter 了
- formatter 的类型就是 value => string 吧，插槽的名字应该叫 default 才对。
- valueStyle 不需要，用户可以通过自定义less 变量或者直接添加 class 就好了。

**Comment by Usualminds** [comment]
- `formatter ` 类型`({value}) => string` 建议修改为 `(value) => string`，`v-slot` 是什么场景，这里直接通过插槽自定义格式，应该可行？

**Comment by clfeng** [comment]
> * `formatter ` 类型`({value}) => string` 建议修改为 `(value) => string`，`v-slot` 是什么场景，这里直接通过插槽自定义格式，应该可行？

这里感觉是一个考虑点，一开始的话是打算直接value，但是后面有觉得formatter的参数如果是一个对象，是不是更好一点？方便以后扩展？不过可能确实是比较难以理解，毕竟我看antd的时候，也是通过demo是用才理解的。可能已函数参数的数量增加作为后续扩展的考虑会好点
