### ISSUE TITLE
[comp:other] 新增组件 loading-bar

### ISSUE THREAD

**Issue by danranVm** [IDuxFE/idux#971]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
## What problem does this feature solve?
全局 loading 的问题。

![image](https://user-images.githubusercontent.com/25052421/174987802-2cd043f6-1762-4d9d-bc42-0f48d5c254f7.png)

## What does the proposed API look like?
- status: loading | finish | error,  加载状态
- mask: boolean， 是否显示遮罩

最好提供一个 provider， 然后提供 useLoadingBar 的 API 形式调用。

**Comment by qingshan-dev** [comment]
yes

**Comment by qingshan-dev** [comment]
fix
