### ISSUE TITLE
[comp:card] 支持选中和禁用功能

### ISSUE THREAD

**Issue by danranVm** [IDuxFE/idux#972]
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
## What problem does this feature solve?
![image](https://user-images.githubusercontent.com/25052421/174989295-8db26dcd-d8df-454c-b608-c5ab0534c527.png)

## What does the proposed API look like?
- selected: boolean 选中状态
- disabled: boolean 禁用状态

暂时先不提供单选多选的样式区分，先统一使用多选样式。

**Comment by lionnnnn** [comment]
11
