### ISSUE TITLE
[comp: Pagination] add Pagination component

### ISSUE THREAD

**Issue by zymoplastic** [IduxFE/idux#98]
- [x] I have searched the [issues](https://github.com/IduxFE/components/issues) of this repository and believe that this is not a duplicate.

#### Props

| 名称 | 说明 | 类型  | 默认值 | 全局配置 | 备注 |
| --- | --- | --- | --- | --- | --- |
| `v-model:pageIndex` | 当前页数 | `number` | `1` | - | - |
| `v-model:pageSize` | 每页条数 | `number` | `10` | ✅ | - |
| `disabled` | 是否禁用 | `boolean` | `false` | - | - |
| `itemRender` | 用于自定义页码的结构 | `PaginationItemRenderFn \| v-slot:item` | `false` | ✅ | - |
| `pageSizeOptions` | 指定每页可以显示多少条 | `number[]` | `[10, 20, 50, 100]` | ✅ | - |
| `responsive` | 当 `pageSize < 1` 时，根据屏幕宽度自动调整尺寸 | `boolean` | `false` | ✅ | - |
| `showQuickJumper` | 是否可以快速跳转至某页 | `boolean` | `false` | ✅ | - |
| `showSizeChanger` | 是否是否可以改变 `pageSize` | `boolean` | `false` | ✅ | - |
| `showTitle` | 是否显示原生 `title` 页码提示 | `boolean` | `false` | ✅ | - |
| `simple` | 显示为简单分页 | `boolean` | `false` | ✅ | - |
| `size` | 分页组件大小 | `middle \| small` | `middle` | ✅ | - |
| `total` | 数据总数 | `number` | `0` | - | - |
| `totalRender` | 用于显示数据总量和当前数据顺序 | `PaginationTotalRenderFn \| v-slot:total` | - | ✅ | - |

#### Slots

| 名称 | 说明 | 参数类型 | 备注 |
| --- | --- | --- | --- |
| `item` | 用于自定义页码的结构 | `{ pageIndex: number; type: PaginationItemType }` | - |
| `total` | 用于显示数据总量和当前数据顺序 | `{ total: number; range: [number, number] }` | - |

**Comment by danranVm** [comment]
@hele10086 @danranVm 负责此组件的 review， API 设计完成后请 `@` 他们
